### ISSUE TITLE
GlArab wont work

### ISSUE THREAD

**Issue by mryoshi5** [Shani-08/ShaniXBMCWork#114]
Hi, thanks for all your work

GLarab wont open. Its says failed paying from GlArab. I have an account and it used to work perfectly....

**Comment by allouch89** [comment]
They seem to have changed the Med and HD ip's again. The Low ip's are still working as far as i can see.

**Comment by mryoshi5** [comment]
Will there be a fix soon? I enjoy watching my arabic channels

**Comment by allouch89** [comment]
Im sure the master minds of shani workers/supporters will fix this issue soon.
It happened late yesterday, so give it alittle bit of time.

**Comment by mryoshi5** [comment]
Ok Thanks for the quick reply btw

**Comment by allouch89** [comment]
Your welcome.

**Comment by Shani-08** [comment]
Thaks to allouch89, we have updated the ips. please try now

**Comment by allouch89** [comment]
Im afraid these IP's only work with Med quality and not HD, and since there is alot of channels only in HD, we desperately need new IP's for HD links
