### ISSUE TITLE
Livetv.tn source missing channels

### ISSUE THREAD

**Issue by hawwach** [Shani-08/ShaniXBMCWork#118]
Hey guys,
A lot of channels are missing in Livetv.tn source.
Any chances for adding them?
I Have the full list if needed since I have a subscription

**Comment by allouch89** [comment]
I guess if you send the list that would solve the problem :)

**Comment by hawwach** [comment]
yes Sir I do have them, how should I send it to you?

**Comment by allouch89** [comment]
Im not sure i can do it, but i guess i can try.
You can send them to my email; allouch@live.dk

**Comment by hawwach** [comment]
Ok thanks in advance, I'll send you the list

**Comment by allouch89** [comment]
Your welcome.
I have actually never used livetv.tn, do you need a login to be able to watch from there?

**Comment by hawwach** [comment]
You must have a subscription code to be able to use livetv.tn. The quality is good. They have several HD channels.

**Comment by allouch89** [comment]
Sounds good.

**Comment by hawwach** [comment]
I've sent you the mail.

**Comment by allouch89** [comment]
The channels in the livetv.tn file is added in this way:
 <cname>Eurosport 2 France</cname>
<chnumber>ch905</chnumber>
<link>http://www.livetv.tn/EuroSport-HD-2-en-direct-live.html</link>
You have sent me the 'cname' and 'chnumber' but the 'link' is still missing and i dont know how to get it.

**Comment by allouch89** [comment]
cname: Eurosport 2 France
chnumber: ch905
link: http://www.livetv.tn/EuroSport-HD-2-en-direct-live.html

**Comment by hawwach** [comment]
It's like this: rtmp://iptv.livetv.tn/live/ch76 with the subscription code at the end

**Comment by hawwach** [comment]
Here's an example for an expired code:
Abu Dhabi 
rtmp://iptv.livetv.tn/live/ch80?code=16ba09c2b16dd6c

**Comment by allouch89** [comment]
I know that, but in shani plugin, we need the link on the website aswell;
example: http://www.livetv.tn/EuroSport-HD-2-en-direct-live.html

**Comment by hawwach** [comment]
Oh I see, if it's for the website, it's something like this:
http://www.livetv.tn/forvip/Bein-Sport-HD-13-en-direct-live.html

**Comment by allouch89** [comment]
yes just without the forvip/ so it will be:
http://www.livetv.tn/Bein-Sport-HD-13-en-direct-live.html

**Comment by allouch89** [comment]
I think you have to get a link for every channel , unless someone else know how to get it .
But if i am going to add the channels for you, you will have to send me a link for every channel

**Comment by hawwach** [comment]
Ok I'll do it this way

**Comment by hawwach** [comment]
Could you please try those to check if it's ok

cname: Bein Sport HD 11
chnumber: ch866
link: http://www.livetv.tn/Bein-Sport-HD-11-en-direct-live.html

cname: Bein Sport HD 12
chnumber: ch870
link: http://www.livetv.tn/Bein-Sport-HD-12-en-direct-live.html

cname: Bein Sport HD 13
chnumber: ch872
link: http://www.livetv.tn/Bein-Sport-HD-13-en-direct-live.html

cname: Bein Sport HD 14
chnumber: ch869
link: http://www.livetv.tn/Bein-Sport-HD-14-en-direct-live.html

cname: Bein Sport HD 15
chnumber: ch868
link: http://www.livetv.tn/Bein-Sport-HD-15-en-direct-live.html

**Comment by allouch89** [comment]
I cant access the website links without a subscription, but i think that it is good.

**Comment by hassuni** [comment]
@hawwach esay way for evryboy,  do a pull request by adding the messing channels .
https://github.com/Shani-08/ShaniXBMCWork/blob/master/plugin.video.shahidmbcnet/resources/community/livetvUrls.xml

**Comment by hawwach** [comment]
Thanks Hassuni, i'll try it right now.
