### ISSUE TITLE
Best TV Box

### ISSUE THREAD

**Issue by allouch89** [Shani-08/ShaniXBMCWork#123]
I have a Best TV Box, i would like to extract the streams from it, anyone that can help me do that?
I have tried with Microsoft Network Monitor, nothing is showing up there.

**Comment by emadmahdi** [comment]
I suggest you install a proxy software on your PC ... then setup your TV Box to access the internet through that proxy ... then install on your PC a network monitor tool such as Wireshark to analyze the traffic using both TCP & UDP.

**Comment by Shani-08** [comment]
This is not a platform for this type of discussion. Lease find s forum to ask this question.

**Comment by allouch89** [comment]
I wish we could write private messages on github..
I have found some channels that we can use but i need to analize the traffic and i dont know how to do that exactly, only with HTTP but these streams is with rtmp and thats TCP/UDP traffic.

**Comment by Shani-08** [comment]
I also wish you learn where to post these messages as you are posting on a closed issues. 
Form now on I won't bother to answer any questions if it's not posted in right place. 

To answer your question, use either email or http://www.tvaddons.ag and make sure ask in the livestream forum.
