### ISSUE TITLE
Gl Arab links

### ISSUE THREAD

**Issue by jmikha4** [Shani-08/ShaniXBMCWork#124]
I have noticed that all gl arab links doesn't work except for the low quality links.
I used the ips that are in 'Try All' and they work in my computer. I tried to debug and see the links and i found that it reads different ip from the assigned ones. 
For example:
Med ip was: 8.21.48.20:7777
HD ip was: 8.21.48.19:7777
which aren't in the GLArabServerMED & GLArabServerHD
I was wondering if anyone can debug and fix this problem?
thank you

**Comment by Shani-08** [comment]
In the HD servers, there is no server for HD other than only one which is not respdonding. Are you saying that 8.21.48.19:7777 is working on your computer? if not which one is working on your computer?

**Comment by jmikha4** [comment]
the one that is working is 38.99.146.158:7777 which is in the GLARABServerHD in setting.xml 
and It's working on my computer but 8.21.48.19:7777 is the one that the program use when I try to open any channel from the program

**Comment by Shani-08** [comment]
which program? and what are the parameters, its possible they have changed the parameters?

**Comment by Shani-08** [comment]
You can email me a taacc14 at g mail com

**Comment by jmikha4** [comment]
is it 'taacc14'?

**Comment by Shani-08** [comment]
yes

**Comment by jmikha4** [comment]
did you get my email?

**Comment by Shani-08** [comment]
nope

**Comment by jmikha4** [comment]
I sent it 20 minutes ago. may be its in spam list?

**Comment by Shani-08** [comment]
yep spam it is

**Comment by Shani-08** [comment]
Replied, please read the email. it will buffer on HD and premium Med channels.
