### ISSUE TITLE
trouble with livetv.tn

### ISSUE THREAD

**Issue by rsalimov** [Shani-08/ShaniXBMCWork#132]
please tell me if the script of livetv.tn work with you, for me i have a standard acount in it but i can't watch any channel
please help.

**Comment by hawwach** [comment]
It works for me on a premium account

**Comment by rsalimov** [comment]
thanx for reply,
but there are free channels for no premium but not working, also i can't watch from the web site after i login.do you think that the web site does't work for free account? 
if not what must i do?

**Comment by hawwach** [comment]
The free channels are working using free account.

**Comment by norhan76** [comment]
Hi, I'm having trouble with the channels on shahid on xbmc, they are buffering a lot. Is there any solution for that thanks

**Comment by hawwach** [comment]
Use sources other that GLARAB @norhan76

**Comment by norhan76** [comment]
Np, r u guys fixing GLARAB soon bec it has a lot of channels.

**Comment by emadmahdi** [comment]
Unfortunately ... there is nothing that we can do to fix glarab except waiting for them to fix there own service.

**Comment by Shani-08** [comment]
I am not 100% sure as those servers which used to work are not down but returning no data. Not even 404 Etc. So it would be great if someone has any gl box which plays premium channels as it would tell is what they are excepting.

**Comment by norhan76** [comment]
I downloaded their app on my ipad and their channels are working great, but
same channels are buffering on shahid.

On Wed, Jan 14, 2015 at 6:00 PM, Shani-08 <notifications@github.com> wrote:

> I am not 100% sure as those servers which used to work are not down but
> returning no data. Not even 404 Etc. So it would be great if someone has
> any gl box which plays premium channels as it would tell is what they are
> excepting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shani-08/ShaniXBMCWork/issues/132#issuecomment-70010156>
> .
>



-- 
Norhan Hammad
Web/Graphic Designer
Phone: (302)743-7697

**Comment by emadmahdi** [comment]
@Shani-08 ... As I remember :

1- The ip 158 for med & hd is a new ip that started bad and still being bad.
2- The ones that was ok for med & hd are the 19, 20, 36, & 37 but none of them is available now.

As for pc & mobile glarab clients ... they does not use any premium channels ... which means they does not use the 158 ... they instead use the other 7 ip's that is available for the ordinary med channels or they use the other 4 ip's that is available for the ordinary low channels.

Currently ... only the 4 servers used for the low quality channels are still available ... but only available for ordinary channels ... and nothing premium is available as low quality.

**Comment by allouch89** [comment]
only low IP's are working for glarab and glturk at the moment. I have tried to see if i could find anything new, nothing came up.

**Comment by allouch89** [comment]
Btw.
if you have http_proxy.exe installed, you can use the localhost:4500/channel.flv to watch gl channels with all the IP's we have used so far. Maybe someone can figure out what localhost:4500 is pointing to?

**Comment by allouch89** [comment]
For example:
http://localhost:4500/channel.flv?server=8.21.48.20&channel=AlJadeed_HD&port=2077&session=8c86e43b93b286f44520181d39d93b5cc6c56d7f5a9de18b2e4c3ef359fee175a299017ce29bf1aa

**Comment by emadmahdi** [comment]
@allouch89 ... the glarab proxy does not support any premium channels or hd channels ... it offer around 150 channels ... some of them are still med quality & the rest are now changed to be low quality ... if you want to use these 150 channels but with Shani's xbmc plugin "Shahid Arabic" then you have to set all of them as low quality.

BTW ... You can test the glarab proxy by visiting "www.glarab.com" website ... or by installing the xbmc "plugin.video.glarab" (github of hadynz) and configure it to use glarab proxy from your pc.

**Comment by allouch89** [comment]
It does work, try the link I sent, it's aljadeed in HD. But I guess it's not worth it anyway, since we need a PC to run the proxy whenever we want to watch anything from glarab

**Comment by emadmahdi** [comment]
i know it do work ... i have both installed ... but as I said ... the proxy method:
1- needs glarab proxy
2- does not have med quality
3- does not have hd quality
4- does not have premium channels
5- same channels of same low quality are still working correctly without buffering using shani's plugin

**Comment by allouch89** [comment]
Al jadeed is premium channel and it's in HD so I don't know where you are getting your information from . But all of this don't matter, the proxy is useless to me and most likely almost everyone

**Comment by emadmahdi** [comment]
@allouch89 ... i am getting my information from my personal research ... if you don't like it then simply ignore it.

A month ago ... the proxy method was exactly as I mentioned but now after the changes that glarab did ... it looks like they also moved lots of their channels from the non-proxy method to the proxy method.

i am still investigating the proxy method and hopefully will publish my findings soon.

@Shani-08 ... i will close this conversation for now and will open a new one as soon as i finish my investigations regarding the proxy method of glarab streaming ... let me know if you do mind publishing it publicly.

**Comment by Shani-08** [comment]
It's ok to close it. 
Your work or your work, do whatever you want, Publish it or not. 
But I would suggest to use emails for early days till we get somewhere. Once we have some success, it's your decision to do whatever you want. 
Proxy method is just a udp client that communicates with the server. Are we saying that proxy is allowing to play channels hd channels which are not available as free or via m3u8 file links?

More on emails. Taacc14 at g m ail .c om

**Comment by allouch89** [comment]
Proxy seems to have all channels, low+med+hd.

**Comment by emadmahdi** [comment]
@allouch89 ... Does it have any of these in any quality ??!!!!!
Rotana Aflam
Rotana Classic
Rotana Cinema

**Comment by allouch89** [comment]
No it doesnt.. My bad.

**Comment by szudena** [comment]
hi guys just change HD to High for some channels
example
http://localhost:4500/channel.flv?server=8.21.48.20&channel=RotanaAflam_High
you dont need session or port

**Comment by emadmahdi** [comment]
Thanks for the info ... Yesterday we added the _High ... You  might need to do download to update your channels list.
