### ISSUE TITLE
GLARAB servers

### ISSUE THREAD

**Issue by jack2023** [Shani-08/ShaniXBMCWork#137]
Hi shani ,
I have a list here of medium quality glaram streams it open fine with vlc player using computer and after installing the software downloaded from glarab website   glarab_http_proxy-1.6.0.10628
I noticed in shahid xbmc you bypassed the proxy issue so when i put the list in live xbmc it doesn't work. Here is the list
#EXTM3U
#EXTINF:-1,Tunisie7 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Tunisie7_Med&
#EXTINF:-1,Hannibal
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Hannibal_Med&
#EXTINF:-1,AlMaghribia
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlMaghribia_Med&
#EXTINF:-1,CanalAlgerie
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=CanalAlgerie_Med&
#EXTINF:-1,M2Morocco 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=M2Morocco_Med&
#EXTINF:-1,Medi1
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Medi1_Med&
#EXTINF:-1,Libya 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Libya_Med&
#EXTINF:-1,Thalitha
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Thalitha_Med&
#EXTINF:-1,AlAoulaEurope
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAoulaEurope_Med&
#EXTINF:-1,Arrabiaa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Arrabiaa_Med&
#EXTINF:-1,Arryadia
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Arryadia_Med&
#EXTINF:-1,Assadissa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Assadissa_Med&
#EXTINF:-1,Tamazight
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Tamazight_Med&
#EXTINF:-1,Libya AlAhrar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAhrar_Med&
#EXTINF:-1,Nessma
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Nessma_Med&
#EXTINF:-1,abudhabi al oula
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ADAlOula_Med&
#EXTINF:-1,Infinity
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Infinity_Med&
#EXTINF:-1,KuwaitSpace
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=KuwaitSpace_Med&
#EXTINF:-1,AlEkhbariya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlEkhbariya_Med&
#EXTINF:-1,SaudiArabia1
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=SaudiArabia1_Med&
#EXTINF:-1,AlBaghdadia 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlBaghdadia_Med&
#EXTINF:-1,Baghdad
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Baghdad_Med&
#EXTINF:-1,AlhurraIraq 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlhurraIraq_Med&
#EXTINF:-1,Funoon
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Funoon_Med& 
#EXTINF:-1,AldiyarSat 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AldiyarSat_Med& 
#EXTINF:-1,Alwatan
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Alwatan_Med&
#EXTINF:-1,AjyalTV 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AjyalTV_Med&
#EXTINF:-1,HodHod
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=HodHod_Med&
#EXTINF:-1,AlThakafiyah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlThakafiyah_Med&
#EXTINF:-1,AlwatanPlus
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlwatanPlus_Med&
#EXTINF:-1,Wanasah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Wanasah_Med&
#EXTINF:-1,MusicPlus
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=MusicPlus_Med&
#EXTINF:-1,Nojoom1
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Nojoom1_Med&
#EXTINF:-1,Beladi
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Belad_Med&
#EXTINF:-1,AlSharqiya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlSharqiya_Med&
#EXTINF:-1,SamaDubai
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=SamaDubai_Med&
#EXTINF:-1,AlEqtisadiyah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlEqtisadiyah_Med&
#EXTINF:-1,Bahrain
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Bahrain_Med&
#EXTINF:-1,OyounJeddah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=OyounJeddah_Med&
#EXTINF:-1,Oman
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Oman_Med&
#EXTINF:-1,AlRafidain
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlRafidain_Med&
#EXTINF:-1,Alsumaria
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Alsumaria_Med&
#EXTINF:-1,KTV2Kuwait
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=KTV2Kuwait_Med&
#EXTINF:-1,KSA2
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=KSA2_Med&
#EXTINF:-1,Ajman
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Ajman_Med&
#EXTINF:-1,Massaya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Massaya_Med&
#EXTINF:-1,AlBabeleyia
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlBabeleyia_Med&
#EXTINF:-1,DubaiEurope
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=DubaiEurope_Med&
#EXTINF:-1,Qatar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Qatar_Med&
#EXTINF:-1,Ishtar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Ishtar_Med&
#EXTINF:-1,AlFayhaa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlFayhaa_Med&
#EXTINF:-1,AlIraqiya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlIraqiya_Med&
#EXTINF:-1,KTV3Plus
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=KTV3Plus_Med&
#EXTINF:-1,AlRiyadiah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlRiyadiah_Med&
#EXTINF:-1,AlDawriAlKassSport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlDawriAlKassSport_Med&
#EXTINF:-1,DubaiSports
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=DubaiSports_Med&
#EXTINF:-1,GearOne
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=GearOne_Med&
#EXTINF:-1,BahrainSport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=BahrainSport_Med&
#EXTINF:-1,Yemen
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Yemen_Med&
#EXTINF:-1,DM
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=DM_Med&
#EXTINF:-1,AlmajdSpace
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlmajdSpace_Med&
#EXTINF:-1,AlMasar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlMasar_Med&
#EXTINF:-1,AlQuran
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlQuran_Med&
#EXTINF:-1,AlSunnah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlSunnah_Med&
#EXTINF:-1,Huda
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Huda_Med&
#EXTINF:-1,Iqraa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Iqraa_Med&
#EXTINF:-1,AlSabah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlSabah_Med&
#EXTINF:-1,AlAnwar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAnwar_Med&
#EXTINF:-1,AlAdala
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAdala_Med&
#EXTINF:-1,AlKout
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlKout_Med&
#EXTINF:-1,AlForat
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlForat_Med&
#EXTINF:-1,ADSport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ADSport_Med&
#EXTINF:-1,AlJazeeraEnglish
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlJazeeraEnglish_Med&
#EXTINF:-1,SharjahTV
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=SharjahTV_Med&
#EXTINF:-1,AlJazeeraGlobalS
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlJazeeraGlobalS_Med&
#EXTINF:-1,Aden
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Aden_Med&
#EXTINF:-1,AlAmakenDrama
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAmakenDrama_Med&
#EXTINF:-1,AlResala
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlResala_Med&
#EXTINF:-1,AlShaab
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlShaab_Med&
#EXTINF:-1,Durrah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Durrah_Med&
#EXTINF:-1,NoorDubai
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NoorDubai_Med&
#EXTINF:-1,ScopeTV
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ScopeTV_Med&
#EXTINF:-1,automoto
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ScopeTV_Med&
#EXTINF:-1,AlsharqiyaNews
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlsharqiyaNews_Med&
#EXTINF:-1,AlRasheed
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlRasheed_Med&
#EXTINF:-1,MTVLebanon
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=MTVLebanon_Med&
#EXTINF:-1,AlJadeed
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlJadeed_Med&
#EXTINF:-1,TeleLiban
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=TeleLiban_Med&
#EXTINF:-1,SyriaDrama
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=SyriaDrama_Med&
#EXTINF:-1,SyriaSat
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=SyriaSat_Med&
#EXTINF:-1,NBNLebanon
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NBNLebanon_Med&
#EXTINF:-1,Heya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Heya_Med&
#EXTINF:-1,AlOrdon
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlOrdon_Med&
#EXTINF:-1,Nourmina
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Nourmina_Med&
#EXTINF:-1,AlHaqeeqa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlHaqeeqa_Med&
#EXTINF:-1,Aghanina
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Aghanina_Med&
#EXTINF:-1,ToyorAlJanah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ToyorAlJanah_Med&
#EXTINF:-1,AlManar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlManar_Med&
#EXTINF:-1,Al Aqsa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AqsaSatCh_Med&
#EXTINF:-1,Palestine
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Palestinian_Med&
#EXTINF:-1,Alquds
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Alquds_Med&
#EXTINF:-1,Mara7
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Mara7_Med&
#EXTINF:-1,Palestine AlYawm
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=PalestineAlYawm_Med&
#EXTINF:-1,Addounia
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Addounia_Med&
#EXTINF:-1,ArabicaMusic
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ArabicaMusic_Med&
#EXTINF:-1,Roya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Roya_Med&
#EXTINF:-1,Mahbooba
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Mahbooba_Med&
#EXTINF:-1,Karameesh
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Karameesh_Med&
#EXTINF:-1,7Stars
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=7Stars_Med&
#EXTINF:-1,Zweina Baladna
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ZweinaBaladna_Med&
#EXTINF:-1,NourAlShabab
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NourAlShabab_Med&
#EXTINF:-1,NourElSham
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NourElSham_Med&
#EXTINF:-1,Syrian Education
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=SyrianEducation_Med&
#EXTINF:-1,Semsem
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Semsem_Med&
#EXTINF:-1,Noursat
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Noursat_Med&
#EXTINF:-1,MelodyAflam
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=MelodyAflam_Med&
#EXTINF:-1,MelodyHits
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=MelodyHits_Med&
#EXTINF:-1,CairoCinema
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=CairoCinema_Med&
#EXTINF:-1,AlHayatCinema
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlHayatCinema_Med&
#EXTINF:-1,Dream1
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Dream1_Med&
#EXTINF:-1,Dream2
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Dream2_Med&
#EXTINF:-1,AlMasriyah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlMasriyah_Med&
#EXTINF:-1,NileInt
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileInt_Med&
#EXTINF:-1,Ghinwa
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Ghinwa_Med&
#EXTINF:-1,AlAhlyTV
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAhlyTV_Med&
#EXTINF:-1,AutoMoto
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AutoMoto_Med&
#EXTINF:-1,Tayba
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Tayba_Med&
#EXTINF:-1,ElMehwar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ElMehwar_Med&
#EXTINF:-1,Sudan
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Sudan_Med&
#EXTINF:-1,BlueNile
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=BlueNile_Med&
#EXTINF:-1,Alnas
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Alnas_Med&
#EXTINF:-1,ONTV
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ONTV_Med&
#EXTINF:-1,NileSport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileSport_Med&
#EXTINF:-1,NileCinema
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileCinema_Med&
#EXTINF:-1,CTVEgypt
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=CTVEgypt_Med&
#EXTINF:-1,AlHayat
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlHayat_Med&
#EXTINF:-1,RTD
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=RTD_Med&
#EXTINF:-1,NileComedy
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileComedy_Med&
#EXTINF:-1,NileDrama
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileDrama_Med&
#EXTINF:-1,Aghapy
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Aghapy_Med&
#EXTINF:-1,AlRahma
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlRahma_Med&
#EXTINF:-1,AlThanya
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlThanya_Med&
#EXTINF:-1,NileDrama2
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileDrama2_Med&
#EXTINF:-1,Misr25
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Misr25_Med&
#EXTINF:-1,Tahrir
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Tahrir_Med&
#EXTINF:-1,RussiyaAlYaum
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=RussiyaAlYaum_Med&
#EXTINF:-1,BBCArabic
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=BBCArabic_Med&
#EXTINF:-1,France24Arabic
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=France24Arabic_Med&
#EXTINF:-1,CCTVArabia
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=CCTVArabia_Med&
#EXTINF:-1,DWTVArabia
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=DWTVArabia_Med&
#EXTINF:-1,MeaTV
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=MeaTV_Med&
#EXTINF:-1,iFilm
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=iFilm_Med&
#EXTINF:-1,AlHiwar
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlHiwar_Med&
#EXTINF:-1,AlAlam
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAlam_Med&
#EXTINF:-1,AlMustakila
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlMustakila_Med&
#EXTINF:-1,TRTArabic
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=TRTArabic_Med&
#EXTINF:-1,AAAMusic
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AAAMusic_Med&
#EXTINF:-1,AlAhlyTV 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlAhlyTV_Med&
#EXTINF:-1,BahrainSpor
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=BahrainSport_Med&
#EXTINF:-1,NileSport 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileSport_Med&
#EXTINF:-1,ModernSpor
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ModernSport_Med& 
#EXTINF:-1,DubaiSports 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=DubaiSports_Med& 
#EXTINF:-1,AlRiyadiah
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlRiyadiah_Med&
#EXTINF:-1,AlJazeeraGlobalS 
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlJazeeraGlobalS_Med&
#EXTINF:-1,ADSport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=ADSport_Med&
#EXTINF:-1,nile sport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=NileSport_Med&
#EXTINF:-1,kuwait sport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=KTV3Plus_Med&
#EXTINF:-1,aldawri
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AlDawriAlKassSport_Med&
#EXTINF:-1,gearone
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=GearOne_Med&
#EXTINF:-1,maroc sport
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=Arryadia_Med&
#EXTINF:-1,automoto
http://achams.com/HDboxTV/ajax.php?stream=live&type=reg&ppoint=AutoMoto_Med&

**Comment by Shani-08** [comment]
These are same links as we have but requires gl proxy. You have an option now to specify the proxy int the settings. Do that and the HD and med channels would work.
