### ISSUE TITLE
ShahidArabic

### ISSUE THREAD

**Issue by relax1000** [Shani-08/ShaniXBMCWork#140]
Hey shani :)

I am missing the arabs got talent section in shahid MBC. maybe you have an option to fix/add that? :)

Thank you

**Comment by Shani-08** [comment]
Its already there, look into MBC4, in Vod by channels

**Comment by relax1000** [comment]
Thanks shani 😃
Another question is glarab working?
Am 19.01.2015 20:57 schrieb "Shani-08" <notifications@github.com>:

**Comment by Shani-08** [comment]
No, only the low channels are working and not all of them, mostly which are available on gl site in low quality are working. If you install proxy then some medium would start working. HD are not working, other than couple.
