### ISSUE TITLE
Help please!!!

### ISSUE THREAD

**Issue by rsalimov** [Shani-08/ShaniXBMCWork#143]
first, thank you shani and your colaborators for this great work.
second, iplease can you explain me how livetv.tn source work?
must i have a premium account or just a free account let me watch at least free channels.
i entered my login information but no thing work, it tell me "enable to get code from..."

**Comment by rsalimov** [comment]
third, i have bout a satellite box from algerie that is under linux (Geant gn-cx88 hd plus) and it contain some iptv channels, i want to know how can i retreive iptv links, i tried to access into it but it's impossible; i used wireshark but the requests are like udp broadcast i'll put some lines of my capture;
and the same think when i installed a proxy in my computer and configured the proxy line in the box to my computer with wireshark working. is there other way to get those links because there is osn channels and i want to get it.
thanx for help

**Comment by Shani-08** [comment]
Live.tn works with premium account, however, with free you can watch the channels that are available free on their site. Check their site if first for working channels. 
For the box, the best case would be getting the software from the box, but there must be some calls going for channels list so wire shark should be the way forward. Upd is probably when you play, so find channels list etc.

**Comment by rsalimov** [comment]
thank you for reply.
the software update is available in this link: http://www.gulfup.com/?kgPFoh
it is a bin file that i can't extract it.
when using file manager installed in the box you can only access to the shared folde.

**Comment by rsalimov** [comment]
there is some information for the box:
 les details
Pnx8471 HD CA +HDMI+LAN
FP:x32 3046
CPu:PNX8471
SPI Flash:2MB
Nad Flash:256MB
DDR:2GB
Encrypt:CA
Official site:
http://www.zinetsatdw.com/index.php/2-uncategorised/59-gn-88-77-hd-2
RCU:039-V3
OSD:ICEBLUE
System:linux
Demod:DS3103
