### ISSUE TITLE
glarab session id problem

### ISSUE THREAD

**Issue by emadmahdi** [Shani-08/ShaniXBMCWork#145]
@Shani-08 ... glarab had changed the page that provides the session id and that caused most servers to stop working for both methods proxy & non-proxy.

**Comment by Shani-08** [comment]
It's has been fixed for few hour. Click download.

**Comment by emadmahdi** [comment]
i did download ... then i checked some channels ... then checked the log file ... still no sessions id at all.

**Comment by Shani-08** [comment]
Oh i see. Naughty naughty of them changing twice in a same day. Click download after 5 mins and it should ok ;)

**Comment by allouch89** [comment]
Good job @Shani-08

**Comment by emadmahdi** [comment]
Thanks @Shani-08 it is ok now.
