### ISSUE TITLE
Adding LR quality to glarab

### ISSUE THREAD

**Issue by emadmahdi** [Shani-08/ShaniXBMCWork#160]
@Shani-08 ... could you please add the LR quality to glarab ... it is less than the Low but it is a great saving of bandwidth.

These are the working ip's and examples for the Proxy LR quality

http://localhost:4500/channel.flv?channel=AlForat_LR&server=8.21.48.116&port=2077
http://localhost:4500/channel.flv?channel=AlForat_LR&server=8.21.48.117&port=2077

**Comment by allouch89** [comment]
You dont need port or session in the proxy method

**Comment by emadmahdi** [comment]
These are just samples ... plus it depends on the server ... though i do recommend adding sessionID for all glarab urls even if it works without it.

**Comment by Shani-08** [comment]
We are potentially going to change the format, as we are discussing in other issue. close closing it here.
