### ISSUE TITLE
Hosting Generic and Official Urls

### ISSUE THREAD

**Issue by Shani-08** [Shani-08/ShaniXBMCWork#164]
Hi guys,
I need someone from you to host these two files, would be great to host on github so that it could be modified. I will update the addon to read the file from your location. Let me know who can do that.
Also, keep making backup, just in case.
@hassuni @emadmahdi

**Comment by Shani-08** [comment]
Please create a new repo or use the existing one, create the file with same name and copy the contents over, let me know the Url, i want to clean the addon as there is nothing else wrong other than direct links to servers, if any.

**Comment by Shani-08** [comment]
@hawwach i need to release the new version so please act quickly

**Comment by emadmahdi** [comment]
@Shani-08 ... i think @hassuni is more active than me ... I am afraid that I will not be available all the time to be able to maintain the file actively.

**Comment by allouch89** [comment]
I just forked it on my account

**Comment by Shani-08** [comment]
Dont fork, create a new repo, add these two files and let me know the url
I am about to push changes

**Comment by Shani-08** [comment]
OK i have to leave so i am releasing it, once you create those two files, update the resources file and enter the url, see other examples there.
People will then fork your repo to send changes

**Comment by hawwach** [comment]
@Shani-08 gonna do it right now, which 2 files exactly?

**Comment by allouch89** [comment]
https://github.com/allouch89/ShaniXBMCdatabase

**Comment by Shani-08** [comment]
lol genericUrls.xml
OfficialUrls.xml

**Comment by allouch89** [comment]
hawwach I believe its genericUrls.xml and OfficialUrls.xml

**Comment by allouch89** [comment]
^^

**Comment by hawwach** [comment]
Ok allouch you've already done it.

**Comment by Shani-08** [comment]
OK, thanks let me update resource file

**Comment by Shani-08** [comment]
Thanks 3.5.0 released with better handling of GL.

**Comment by Shani-08** [comment]
@allouch89 please move IPTVPlanetUrls.xml out to your repo.

**Comment by allouch89** [comment]
Done.
How can i make you contributer?

**Comment by Shani-08** [comment]
Thanks
