### ISSUE TITLE
How do you install the GLarab proxy!!

### ISSUE THREAD

**Issue by moe1999** [Shani-08/ShaniXBMCWork#165]
Is the proxy more efficient?

**Comment by allouch89** [comment]
Download and install: https://www.glarab.com:447/zixi/download/proxy/glarab_http_proxy-1.6.0.10628.exe

I dont know if its more efficent, but its the only options right now to watch HD quality channels with glarab.

**Comment by Shani-08** [comment]
You are comparing watching channels in HD and not watching channels in HD, choose which one you want. You can always watch in Low quality if you dont have proxy or you handicapped because you are not on windows.

**Comment by Shani-08** [comment]
OK a shared proxy is now available in 3.5.1 which means you should be able to run it without local proxy installation. Closing this issue.
