### ISSUE TITLE
Help on akamaihd.net

### ISSUE THREAD

**Issue by rsalimov** [Shani-08/ShaniXBMCWork#167]
hi everyone,
i just want to ask shani to tell me how to make a script in python to retrieve all parametres to play links like : http://pebbles109-lh.akamaihd.net/i/tf1_1@97468/index_1300_av-p.m3u8|X-Forwarded-For=195.186.145.47?
i know mybe xbmc can play it but i want to play it with a player like vlc or android vitamio player.
i have tracked requests sent to akamaihd but responses fails to begins stream; i used headers to set user agent cookies but no chanse.
please i know that you have response to this!

**Comment by Shani-08** [comment]
post the page as the url is inaccessible and i dont have any way to tell you how to!
