### ISSUE TITLE
These few streams of same channel from that device stop after few seconds.

### ISSUE THREAD

**Issue by ykhehra1** [Shani-08/ShaniXBMCWork#169]
These few streams of same channel from that device stop after few seconds. dag use to work before they stop, but these other from same device stop after few seconds. Is there any way to make them work in your plugin. By the way your work is awesome!

DQoNCmh0dHA6Ly9qcHhtbC5qYWRvb3R2LmNvbS92dXhtbC5waHAvamFkb294bWwvcGxheS8zNTENCg0KaHR0cDovL2Rldi5qZW10di5jb20vcWEucGhwLzJfMi9neG1sL3BsYXkvMzIxDQoNCmh0dHA6Ly9mZXJyYXJpbGIuamVtdHYuY29tL2luZGV4LnBocC8yXzIvZ3htbC9wbGF5LzMyMQ0KDQpodHRwOi8vZGFnLnRvdGFsLXN0cmVhbS5uZXQvZGFnMS5hc3g/aWQ9YWQxIXB0Y2NoYWtkZQ0K

I found that p-3-g links in your plugin stop working. So I made little addition to grab new links (need 2 clicks to play. I am not a coder so don't  know how to make it play in one click :) ). You can add it to zemtv and I know you will improve it. here is it:

ZGVmIGMyNDd0dih1cmwpOg0KICAgIHJlcSA9IHVybGxpYjIuUmVxdWVzdCh1cmwpDQogICAgcmVxLmFkZF9oZWFkZXIoJ1VzZXItQWdlbnQnLCAnTW96aWxsYS81LjAoaVBhZDsgVTsgQ1BVIGlQaG9uZSBPUyAzXzIgbGlrZSBNYWMgT1MgWDsgZW4tdXMpIEFwcGxlV2ViS2l0LzUzMS4yMS4xMCAoS0hUTUwsIGxpa2UgR2Vja28pIFZlcnNpb24vNC4wLjQgTW9iaWxlLzdCMzE0IFNhZmFyaS81MzEuMjEuMTAnKQ0KICAgIHJlc3BvbnNlID0gdXJsbGliMi51cmxvcGVuKHJlcSkNCiAgICBsaW5rPXJlc3BvbnNlLnJlYWQoKQ0KICAgIHJlc3BvbnNlLmNsb3NlKCkNCg0KICAgIG1hdGNoPXJlLmNvbXBpbGUoJzxhIGhyZWYgPSIoLis/KSInKS5maW5kYWxsKGxpbmspDQogICAgZm9yIHVybCBpbiBtYXRjaDoNCiAgICAgICAgbmFtZTE9dXJsLnJlcGxhY2UoJ2h0dHA6Ly9jMjQ3LnR2L2xpdmUucGhwP2NoPScsJycpDQogICAgICAgIG5hbWU9bmFtZTEucmVwbGFjZSgnXycsJyAgICcpDQogICAgICAgIGFkZERpcihuYW1lLHVybCw1MDIsJycsIEZhbHNlLCBUcnVlLGlzSXRGb2xkZXI9VHJ1ZSkNCg0KDQpkZWYgYzI0N2xpbmtzKHVybCk6DQogICAgcmVxID0gdXJsbGliMi5SZXF1ZXN0KHVybCkNCiAgICByZXEuYWRkX2hlYWRlcignVXNlci1BZ2VudCcsICdNb3ppbGxhLzUuMChpUGFkOyBVOyBDUFUgaVBob25lIE9TIDNfMiBsaWtlIE1hYyBPUyBYOyBlbi11cykgQXBwbGVXZWJLaXQvNTMxLjIxLjEwIChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi80LjAuNCBNb2JpbGUvN0IzMTQgU2FmYXJpLzUzMS4yMS4xMCcpDQogICAgcmVzcG9uc2UgPSB1cmxsaWIyLnVybG9wZW4ocmVxKQ0KICAgIGxpbms9cmVzcG9uc2UucmVhZCgpDQogICAgcmVzcG9uc2UuY2xvc2UoKQ0KDQogICAgI21hdGNoID1yZS5maW5kYWxsKCd3aWR0aD0oLis/KSwgaGVpZ2h0PSguKz8pLCBjaGFubmVsPVwnKC4rPylcJywgZz1cJyguKz8pXCcnLCBsaW5rLCByZS5ET1RBTEx8cmUuSUdOT1JFQ0FTRSkNCiAgICBtYXRjaD1yZS5jb21waWxlKCd3aWR0aD0oLis/KSwgaGVpZ2h0PSguKz8pLCBjaGFubmVsPSguKz8pLCBnPSguKz8pOzwnKS5maW5kYWxsKGxpbmspDQogICAgZm9yIHcsaCxpZHQsZ2lkIGluIG1hdGNoOg0KICAgICAgICBpZD1pZHQucmVwbGFjZSgnXCcnLCcnKQ0KICAgICAgICBndD1naWQucmVwbGFjZSgnXCcnLCcnKQ0KICAgICAgICB1cmw9J2h0dHA6Ly93d3cucDNnLnR2L2VtYmVkcGxheWVyLycraWQrJy8nK2d0KycvJyt3KycvJytoDQogICAgICAgIGFkZERpcignQ2xpY2sgT0sgdG8gcGxheScsdXJsLDE3LCcnLCBGYWxzZSwgVHJ1ZSxpc0l0Rm9sZGVyPUZhbHNlKQ0KDQo=

**Comment by Shani-08** [comment]
I have updated the links, Dag url will not work without the hash value for which you have to get the url from the source with everything that it needs.

**Comment by ykhehra1** [comment]
I added those links in plugin. Anyways they are working since your last update. Thanks

**Comment by ykhehra1** [comment]
Thanks for better code for adding c 24 7 links with one click play, but HD links (m.i.p.s) not working. I guess when plugin opens page url (e.g. aHR0cDovL3d3dy5taXBzcGxheWVyLmNvbS9lbWJlZHBsYXllci9kb2RlbGl0di8xLzYwMC80MjA=), it returns with 'Link is disabled.'.

Also those couple of links in first post (first encoding) again stop after half second, rest working fine from same source.
