### ISSUE TITLE
Any NEWS of GLarab 

### ISSUE THREAD

**Issue by moe1999** [Shani-08/ShaniXBMCWork#170]
Nothing is working man.  Are you currently working on GLarab.
@Shani-08 
Thanks,

**Comment by allouch89** [comment]
install the gl proxy and go to settings in shahid, enable local proxy.

**Comment by moe1999** [comment]
Is it possible to install it on my box. I have a Amazon fire tv.

**Comment by allouch89** [comment]
Im afraid not, it's only for windows.

> Den 14/02/2015 kl. 18.42 skrev "moe1999" <notifications@github.com>:
> 
> Is it possible to install it on my box. I have a Amazon fire tv. 
> 
> Sent from my iPhone 
>

**Comment by moe1999** [comment]
i can convert exe to apk file! If so i think i can !

**Comment by allouch89** [comment]
Well be my guest and try. But I doubt you can get it working like it is supposed to on mobile devices

**Comment by norhan76** [comment]
Please, let us know if it works. Good luck.

**Comment by moe1999** [comment]
Thanks I sure will!
