### ISSUE TITLE
channel request

### ISSUE THREAD

**Issue by hawwach** [Shani-08/ShaniXBMCWork#175]
hey guys, 
would you please consider adding this channel to African section 
http://www.rti.ci/direct_rti1.html
Thanks.

**Comment by hassuni** [comment]
do a pull request
rtmp://178.248.214.76/rti_str-1806-e125986013b9e7e994a18164ce0fcb48/rti.stream timeout=20

**Comment by hawwach** [comment]
Thanks @hassuni pull request created

**Comment by hawwach** [comment]
Hello hassuni, the link you've provided is not working, how did you locate the streaming url? Using url snooper ?

**Comment by hassuni** [comment]
I thing you need regex for it.
I used urlhelper ver3
ask here for regex
http://forums.tvaddons.ag/threads/17239-Livestreams-and-XML-Request-s-2/page630

rtmp://178.248.214.76/rti_str-0739-6b15ce473c2a491f8b49ebe7a71835fb/<playpath>rti.stream <swfUrl>http://lb.streamakaci.com/streamakaci/library/VideoPlayerStreamakaci.swf <pageUrl>http://lb.streamakaci.com/rti/

**Comment by hassuni** [comment]
fixed thanks to gujal
