### ISSUE TITLE
PTV sports channel

### ISSUE THREAD

**Issue by zafar2002** [Shani-08/ShaniXBMCWork#177]
How can I get PTV sports and Ten sports channel working please. Many thanks in advance and I do apologize if this is already answered. I am new to the site and not sure where to look for.

thanks

Zafar

**Comment by Shani-08** [comment]
get 3.3.8 and make sure you have latest librtmp. check http://forums.tvaddons.ag/threads/19933-Release-Addon-for-Zemtv-com?p=251545&viewfull=1#post251545

**Comment by zafar2002** [comment]
​Hi Shani,
Sorry I was off sick so could not even login to the forum. What do I have
to do, do you have any step by step instructions for getting PTV sports?
many thanks.​

*Sincerely,*
*Zafar Mahmood*
*07450045493*
