### ISSUE TITLE
Zem TV - Other sources down

### ISSUE THREAD

**Issue by jchirag0221** [Shani-08/ShaniXBMCWork#181]
Bhai,

Something gone wrong again with Indian channels. None of the Indian channel works. Also under Pakistani channels only ebound works but nothing under other source. 

Other source had good quality compare to ebound and more options.

May be something changed at the server. Any chance to fix it... Thanks in advance...

**Comment by kodisyd** [comment]
Tried, 3.4.2, Indian channels not working! Please fix, thanks in advance.

**Comment by Criminalised** [comment]
This is down. I signed up on this site for this very reason.  The green links are all not working.  Does nothing after displaying "fetching links".
 Thanks

**Comment by Criminalised** [comment]
Hi, one other thing.  Why am I unable to get sound from the ebound service channels?  I'm on windows by the way. Any help is welcome.

Thanks

**Comment by Shani-08** [comment]
Yes its down and may not come back, the addon will be updated once we know how to fix it, its been closed by the source.

**Comment by jchirag0221** [comment]
Bhai,

Any chance I can help you with. I know the source and looks like they have changed their header validation... Do I need the source box in order to see the code?

**Comment by Shani-08** [comment]
If you have a box and you can look into then let me know.

**Comment by Shani-08** [comment]
Get 3.4.3 and enjoy ;)

**Comment by jchirag0221** [comment]
Bhai, I think its again down. Looks like again changed their header.

**Comment by jchirag0221** [comment]
Sorry, ignore it came back...  Strange, stopped for a bit....
