### ISSUE TITLE
I don't see the channel list under iptvosn

### ISSUE THREAD

**Issue by cs334** [Shani-08/ShaniXBMCWork#184]
Any helpers? I updated my shahid net but I still don't see the list of channels I updated in the XML file of iptvosnchannels.
Shani, do you see the list under your iptvOSN?

Thanks

**Comment by hassuni** [comment]
you need to use the same channel name found in Channels.xml. should be the same uppercase or lowcase and space example Sout El Shaab, if use SoutEl Shaab you will not see.


https://github.com/Shani-08/ShaniXBMCWork/blob/master/plugin.video.shahidmbcnet/resources/community/Channels.xml

**Comment by Shani-08** [comment]
if you updated the xml file then check xml is valid as any issue and it wont display anthing, valid xml via notepad++.
