### ISSUE TITLE
change xbmc.executebuiltin behaviour

### ISSUE THREAD

**Issue by alibbaba** [Shani-08/ShaniXBMCWork#185]
What is happening 
right now if we use this to call another plugin e.g. youtube , it will not return us to Livestream addon anymore when we want to go back.
<item>
<title>Lauch youtube</title>
<link>$doregex[showyoutube]</link>
<regex>
<name>showyoutube</name>
<expres>$pyFunction:xbmc.executebuiltin('ActivateWindow(10025,&quot;plugin://plugin.video.youtube/&quot;)')</expres>
<page></page>
</regex>
</item>
Is it possible to go back to livestreams addon after entering youtube addon like this instead of starting the plugin : Video addons >> Livestreamspro >>

**Comment by Shani-08** [comment]
Shouldn't just using the plugin:// syntax will launch and come back?
Try creating an item with just that and no rejex to see if it works. If so then we just need to do the same. Once that works, your regex should finish with plugin:// no activate windows etc.

**Comment by alibbaba** [comment]
No, plugin:// will not do it. When we use link tag , it expect

Using ActivateWindow feature we can directly enter into a video node or directory of other addon and it is not possible with link tag. For example , I want to go to gensis addon latest episodes directory and it could done like this:
[CODE]<item>
<title>Genesis Episodes</title>
<link>$doregex[showyoutube]</link>
<regex>
<name>showyoutube</name>
<expres>$pyFunction:xbmc.executebuiltin('ActivateWindow(10025,&quot;plugin://plugin.video.genesis/?action=episodes_added&quot;)')</expres>
<page></page>
</regex>
</item>[/CODE] 


It will not show me the directory if i do like this. I guess it expect it to be a playable link which it is not. :
[CODE]<item>
<title>Lauch youtube</title>
<link>plugin://plugin.video.genesis/?action=episodes_added/</link>
</item>[/CODE] 
I hope you understand the problem. Thanks for the reply so quickly.

**Comment by Shani-08** [comment]
Oh so you mean we display the directory from certain addon and when use exit from that addon we should come back to our addon?
I don't know how to achieve as we have moved the control to the other addon.

**Comment by Shani-08** [comment]
I think you got the way working for you already,. closing it,
