### ISSUE TITLE
IPTVPlanet in Linux

### ISSUE THREAD

**Issue by skype007** [Shani-08/ShaniXBMCWork#186]
Hi @Shani-08 
Seems I can play IPTVPlanet sources on Windows (if it works of course) but in Linux there are no IPTVPlanet. Take Art Aflam for example : in Windows there's Teledunet, Shani and IPTVPlanet :) but in Linux only Teledunet and Shani are displayed (no sign of IPTVPlanet).
Don't know if someone else got the problem

**Comment by Shani-08** [comment]
Click download again and check now.

**Comment by skype007** [comment]
Fixed ;) Good work @Shani-08 ;)
