### ISSUE TITLE
Question about Shahid on Kodi for Android

### ISSUE THREAD

**Issue by Protestingrab** [Shani-08/ShaniXBMCWork#188]
I apologize if this is not the right area to ask this question.  First I wanted to say thank you so much for the work you do, I have been enjoying Shahid for over a year now and its brought a lot of happiness to my parents to be able to watch shows from back home.

That being said I recently ran into a problem that started two days ago.  I am running Kodi on a MK809 III android tv stick.  Everything was working great until a few days when GLArab went down, then yesterday it came back up again on my PC but it wont work on my android stick.  All of the preferences are exactly the same as the PC, the application tries the same streams, and connects to the same stream but on the PC it shows up while on my android tv it gives me the "Failed playing from GLArab" error.  I noticed however that its only the GLArab HD sources, for example Al Manar plays fine on the android stick but MTV (The Libnani station) does not. I've tried troubleshooting as much as possible, uninstalling kodi, reinstalling, removing and reinstalling the Shahid app, trying all the proxy settings for GLArab all to no avail. I really am not sure what the next steps I can/should take for troubleshooting are.  Any help you could offer would be much appreciated.  Thank you again so much for the work you do!

**Comment by emadmahdi** [comment]
@Protestingrab

Your said some channels works on the PC but does not work on Android ... the reason simply could be related to the proxy which can run on a PC while it can not run on Android ... here is some more details & explanations.

Glarab live streams & channels can be watched using two methods ... proxy method & non proxy method ... the proxy method needs a small tool called a proxy that should be installed on a PC and works as a translator in the middle between the kodi shahid plugin and the glarab servers ... while the non-proxy method plays the streams directly without the need for any tools in the middle.

As for the channels & streams availability ... some channels are available using both methods while others are available using only one of the two methods.

To my knowledge the proxy itself is available only for Windows PC ... No Android and no other OS is supported ... So to be able to watch the channels that needs the gl proxy then you have to configure your Kodi Shahid Plugin (regardless if it is installed on a PC or Android) to use that proxy ... which simply means if you do not have the gl proxy installed somewhere then you cannot watch the channels that needs the proxy ... hence you can only watch the channels that does not need the gl proxy.

**Comment by emadmahdi** [comment]
@Protestingrab 

You also need to consider that some glarab channels are available using all resolutions while some others are having less availability ... here is an example showing the current available streams for the two tv channels that you mentioned.

>Al Manar<
HD
LOW
proxy HD
proxy MED
proxy LOW
proxy LR

>MTV<
HD
proxy HD
proxy MED
proxy LOW

So if you are using Android and you did not configure shahid plugin to use a gl proxy (installed on some windows pc) ... then all the streams that starts with the word proxy will not work on that Android and will work on the PC (if that PC has the proxy installed on it).

**Comment by allouch89** [comment]
@emadmahdi is the channels working for you?
Because none of the channels are working for me, both proxy and non proxy method.
They stopped working for me 2 or 3 days ago. Its weird, because when i enter the url in the browser, i can download the file but when i enter it in vlc or others, it gives me and error.

**Comment by allouch89** [comment]
HD and Med channels atleast, premium channels

**Comment by Protestingrab** [comment]
Thank you so much for the response I do appreciate it!  The thing for me was that the channels on the android were working as of two days ago MTV GlarabHD worked fine, as did al Jadeed, al ourdiniyyah, etc.  I was using the non-proxy streams.  They stopped working as of two days ago on my android but continued to work on my laptop.

Interestingly enough I now have tried the channels and they have stopped working on my PC as well.  I used them fine about 5-6 hours ago and now they have stopped working (after midnight & the regular Shahid files update)

It actually seems that none of the GLArab streams (proxy and nonproxy) of any resolution are working for me as of now neither on android nor on PC.

I again apologize if this is not the right place for these kinds of questions/troubleshooting, I hope I am not being rude or disrespecting rules on github by posting these kinds of errors/problems.  I guess my real interest is to figure out why streams that worked suddenly stop working, when it is the same program/platform & server that is being used & if there are any established methods of troubleshooting and how I would go about doing so.  Again I want to thank both allouch89 & emadmahdi for their helpful and informative responses and Shani for his amazing work on this add-on.

**Comment by allouch89** [comment]
GLArab keeps changing their servers and settings, we cant really do anything about it except to try and find the the servers and settings when they change it.

You do not need to apologize, you have asked your question at the right place. Better than many others, because they use closed/old issues instead of opening a new issue like you.

**Comment by emadmahdi** [comment]
@Protestingrab ... try to use the non-proxy Low streams ... they are still working ... otherwise you need to wait till someone from shahid plugin development team finds the problem and fix it ... I personally stopped interfering in glarab issues ... regards.
