### ISSUE TITLE
JagoBD

### ISSUE THREAD

**Issue by shuvro68** [Shani-08/ShaniXBMCWork#190]
Hi!
No channels ar working without one.
Can u fix it pls.

Thanks / Shuvro

**Comment by alibbaba** [comment]
token changed it is now  ```%pwrter(nKa@#.``` .

**Comment by Shani-08** [comment]
just checked and its working for me!

**Comment by shuvro68** [comment]
Hi! @Shani-08 
pls fix the jagobd . no channels ar working .

Thanks
