### ISSUE TITLE
Gl Arab Web Service

### ISSUE THREAD

**Issue by mryoshi5** [Shani-08/ShaniXBMCWork#191]
First of all I'd like to thank you guys of all of the hard work. I recently subscribe to the month web service from the gl arab website. I was wondering if i can some how log in on Shahid using my gl arab premium account and watch all the hl arab HD channels. 
Thanks

**Comment by Shani-08** [comment]
Sorry, I haven't used the web subscription myself so not sure if it could be used or not. I am guess not as the urls would need to take care of your user details. give it a try anyways.
