### ISSUE TITLE
playwire links are not being picked!

### ISSUE THREAD

**Issue by saima2** [Shani-08/ShaniXBMCWork#195]
Shani first of all thanks a lot for making this addon! it rocks, and my fav addon.

how ever there is a little problem.

can you please fix thanks a lot!

the addon is not picking up Playwire links that they are using!

so its quite annoying because most of the updates are using playwire so the addon is not playing those video : (

**Comment by Shani-08** [comment]
How many places you going to post this? you are sending msgs, posting in irrelevent threads and now here?
Please post one place and have patience! The addon has been updated though. get 2.4.4

**Comment by saima2** [comment]
Sorry it was because I did not know where to get in touch with you. I then realised github is not the best place since your work is here.

btw the addon is now playing playwire, but it does not load up the next part.

if dramasonline drama update has 4 parts posted in an update, in kodi its only picking up the first not , not jumping to next part.

you might want to fix this in ur next update whenver you have time : )

thanks a lot.
