### ISSUE TITLE
streams last working version 1.6.7 

### ISSUE THREAD

**Issue by hekelezeme** [Shani-08/ShaniXBMCWork#198]
Last working version 1.6.7 for me, gotham 12.3 win xp. On higher versions 1.6.8 , 1.6.9 can't play live streams.

**Comment by alibbaba** [comment]
Is it regex problem. Then, wait for new release.
Can you upload the log into patebin or xbmc log please.

**Comment by Shani-08** [comment]
1.7.0 released

**Comment by hekelezeme** [comment]
log    http://pastebin.com/PQzPSnQL
