### ISSUE TITLE
rtmpdub wowza

### ISSUE THREAD

**Issue by HIGHWAY99** [Shani-08/ShaniXBMCWork#199]
Hey shani, couldn't make an issue on your fork for rtmpdub so figured i'd catch you here, not sure if your on skype at all anymore.

Was curious if you had any ideas as far as LIBRTMP for making it either support the wowz:// protocol or making it refrain from stopping the current streaming url (that actually plays) when the streaming server tries to tell it to netstream.play.reset to a new url with an unsupported protocol such as wowz://.

**Comment by Shani-08** [comment]
send me the example. continuing with current stream should be easier, not sure how wow:// works though so will have a look

**Comment by Shani-08** [comment]
no examples
