### ISSUE TITLE
GLARAB

### ISSUE THREAD

**Issue by moe1999** [Shani-08/ShaniXBMCWork#203]
yo @Shani-08 how can i get the glarab m3u8 file.  i want to play the channels on iptv PVR simple client.
/thanks my nig\

**Comment by allouch89** [comment]
You cant because you need a new session and more every once in a while

**Comment by moe1999** [comment]
is there another and easier way to watch it then.  if not do you have an arabic m3u playlist file

**Comment by moe1999** [comment]
@allouch89

**Comment by allouch89** [comment]
Do you have an android tv box?

**Comment by moe1999** [comment]
Yes

**Comment by allouch89** [comment]
Would you like to try my app?
Email me on allouch@live.dk

**Comment by hassuni** [comment]
@allouch89  I would like to try it.
send it to me. You have my email?

**Comment by allouch89** [comment]
I have somewhere but cant you just send Me an email or send Me Tour email? Thx

**Comment by Shani-08** [comment]
nothing to discuss so closing it
