### ISSUE TITLE
Problems with shahidmbcnet buffering

### ISSUE THREAD

**Issue by BartOtten** [Shani-08/ShaniXBMCWork#206]
A users of Addons.Center reported an issue with Shahid Arabic. I assume you as developer are "the one" to answer it (rather than me doing a half attempt)

link: http://forums.addons.center/thread/61-problems-with-shahidmbcnet/

**Comment by Shani-08** [comment]
get them to create an issue here, the description is too generic to act upon and there are many channel and resources so ask them to provide those and create issue here, i will update the xml for forum details

**Comment by BartOtten** [comment]
Roger that
Op 14 jun. 2015 22:01 schreef "Shani-08" <notifications@github.com>:
