### ISSUE TITLE
Shahid Arabic - buffering problems

### ISSUE THREAD

**Issue by myamak** [Shani-08/ShaniXBMCWork#207]
Hi
I am not an expert with kodi xbmc. However, it is the only way for me to watch most of the arabic channels where i live in Angola.
I have the add on Shahid Arabic version 3.6.2. It worked fine but suddenly it starts making lots of buffering; like working 2 secs then buffering for 30 secs or a min or more.
I tried to fix the problem making the "add 0 cache advanced xml" uing the xunity maintenance add on. However, the problem persists.
I tried several channels (mbc1 and Abu Dhabi for example), different sources and many times.

Is this a known issue?anyone can help me solve it?

**Comment by hassuni** [comment]
try 2M under Maroc source: shani High playTV. it should no buffering.
I did have buffering problem with my "Minix x7", since I changed to Amazon Fire Tv, my problem gone.

**Comment by myamak** [comment]
thanks. but can u tell me more details on how to try the 2M? and everything that i need to change.
sorry but i dont know this program in details..

**Comment by hassuni** [comment]
open shahid addon, go to shahid live---Maroc---2M and click on shani:High playTV.
2M is a channel that you can check if buffering is a source problem or is you connection or your device.

shani:High playTV  is a good source with no buffering

**Comment by Shani-08** [comment]
no response closed..
