### ISSUE TITLE
Mutiple links inside one item

### ISSUE THREAD

**Issue by alibbaba** [Shani-08/ShaniXBMCWork#210]
Is there any reason you have changed this from version 1.7.1 to 1.7.2.

https://github.com/Shani-08/ShaniXBMCWork/commit/c5144077e03ba506f5769187d97f73a27ee05eb7#diff-cea346650697a9f079e380775c48f9a6L685

Basically , It allow us to put multiple links inside one item and ask to choose which item to play instead of default behavior of playing like playlist.

I have make a pull request with appropriate changes. Hope you will consider this.

Thanks

**Comment by Shani-08** [comment]
No reason, must be a mistake. you are allowed to make changes btw, i will release it shortly!
