### ISSUE TITLE
Zem TV Addon Pakistani channels

### ISSUE THREAD

**Issue by alihassan54111** [Shani-08/ShaniXBMCWork#212]
Hi Shani, 
Good to see you here, your addon is very good and im enjoying alot. i use your addon in my Android box and it works fine, but i ve some problems with it, 1st is that last update 3.5.7, you fatch some adds with channels thats why they were not working in XBMC but at the same time they were working in KODI very smoothly. I dont know why. Can you explain me please, why is it like this. Second is that, the in new update some pakistani channels are not comming just like ARY News etc.

**Comment by Shani-08** [comment]
Please use Kodi, as xbmc is not supported anymore and i dont have any setup to test and verify why its not working.
get 3.5.9 and ARY news should be working.

**Comment by alihassan54111** [comment]
Thank you
