### ISSUE TITLE
jagobd not working

### ISSUE THREAD

**Issue by shuvro68** [Shani-08/ShaniXBMCWork#213]
Hi! 
not a single channel ar working.
Can u fix it pls.
Thks

**Comment by Shani-08** [comment]
Are you using version 1.0.9 as its working here fine?

**Comment by alihassan54111** [comment]
Hi, Jago BD .com is not Working. can you fix it Plz.

**Comment by Shani-08** [comment]
Working here. Please check your version.

**Comment by alihassan54111** [comment]
Hi, Jago BD .com is not Working. Can you fix it Plz. When we click on channel, it says Link found but after working channel didn't play. Only ATN Islamic, ATN Music, Bangla TV, Bijoy, Ekattor TV, E TV, SA TV (Bangladesh) and SK TV Bangla is Working and the rest of the channels are not working. Can you Plz fix it. I'll be very great-full to you.

Thank You.
