### ISSUE TITLE
Genesis Commonresolvers setting doesn't work

### ISSUE THREAD

**Issue by KBug** [Shani-08/ShaniXBMCWork#214]
The Genesis Commonresolvers setting doesn't work anymore. It's because Lambda removed the Commonresolvers.py file from Genesis for some reason, so your Commonresolvers setting points to a file that doesn't exist. Quick fix is to point to the older Commonresolvers.py file for Lambda's Hellenic TV add-on. Long term probably either need Lambda to add the file back to Genesis or point the setting to Eldorado's url resolver.

**Comment by alibbaba** [comment]
I have now point it to Urlresolver module directly. It should be fix now.

**Comment by Shani-08** [comment]
Released in 1.8.0
