### ISSUE TITLE
Channel not working 

### ISSUE THREAD

**Issue by kingali00** [Shani-08/ShaniXBMCWork#215]
Can u please fix Yemen today channel it's called in Arabic Yemen alyawm every time I try to startup I'll get a message ( no sources found) please help
Link to live on the internet..
http://yementodaytv.net/m/livestream.php

**Comment by kingali00** [comment]
In shahid Arabic

**Comment by Shani-08** [comment]
should be working now, click download
The audio is little choppy ,on the site.

**Comment by kingali00** [comment]
Thank u very much

**Comment by kingali00** [comment]
I have a question 
All channels are broadcasted off live internet or satellite

**Comment by Shani-08** [comment]
Everything is off Internet
