### ISSUE TITLE
zemtv dailymotion links not working

### ISSUE THREAD

**Issue by saima2** [Shani-08/ShaniXBMCWork#220]
most of the videos on zemtv are dailymotion.

i think dailymotion changed their code, they got a new player and since the addon is not showing any videos from zemtv.

can you please update that code cuz it is the most important part of the addon.

**Comment by Shani-08** [comment]
The change required is in UrlResolver so either wait for that Addon to be updated (its managed by someone else) or update the file manually, open \addons\script.module.urlresolver\lib\urlresolver\plugins\dailymotion.py file and remove these two lines,

imgSrc =''# re.compile('"thumbnail_url":"(.+?)"').findall(link)[0]
common.addon.log('img:' + imgSrc)

**Comment by saima2** [comment]
I did remove those two lines but it did not help. cannot load the dm videos.

I guess I will have to wiat for an update.

Thanks though : )

**Comment by saima2** [comment]
This is how my dm .py file looks like after the edit.

http://pastebin.com/H4058nPB

**Comment by Shani-08** [comment]
get the file from here, it will be released by Eldorado but not sure when,
https://raw.githubusercontent.com/kashiif/script.module.urlresolver/master/lib/urlresolver/plugins/dailymotion.py
