### ISSUE TITLE
Jago BD Addon is Not Working !!!

### ISSUE THREAD

**Issue by alihassan54111** [Shani-08/ShaniXBMCWork#221]
Hi, Jago BD .com is not Working. Can you fix it Plz. When we click on channel, it says Link found but after working channel didn't play. Only ATN Islamic, ATN Music, Bangla TV, Bijoy, Ekattor TV, E TV, SA TV (Bangladesh) and SK TV Bangla is Working and the rest of the channels are not working. Can you Plz fix it. I'll be very great-full to you.

Thank You.

**Comment by Shani-08** [comment]
Try 1.1.0 thanks

**Comment by alihassan54111** [comment]
Not Working. It says, Url Found and thats it. Nothing comes up. Sorry to
bother you again.

**Comment by Shani-08** [comment]
Make sure you are on 1.1.0 and get the updated librtmp, depending on your plateform. see here http://bit.ly/SCLibrtmp
its better if you use kodi 15 same as i am testing

**Comment by shuvro68** [comment]
Still not working can u pls fix it . Thks

**Comment by Shani-08** [comment]
1.1.1 was update in last hour so try that otherwise i am lost!

**Comment by shuvro68** [comment]
I have the new one but sill not working can u pls fix.

**Comment by Shani-08** [comment]
sorry, i tried playing ATN News and it worked so not sure if you are being geo blocked. i tried US vpn too and it worked. so upload the issue log as i can't do anything else here
