### ISSUE TITLE
Shahid Youtube - lebanon not working

### ISSUE THREAD

**Issue by skype007** [Shani-08/ShaniXBMCWork#222]
Hi @Shani-08 ,
There's a problem in Shahid Youtube - Selections by Zombi : everything seems to work except "lebanon". When I click on "lebanon", the list is empty. According to kodi.log : 

3:00:14 T:139763298125568  NOTICE: youtube url is https://raw.githubusercontent.com/zombiB/ShahidTube/master/lebanon/lebdir.xml
13:00:14 T:139763298125568  NOTICE: 19
13:00:14 T:139763298125568  NOTICE: somethingwrong
13:00:14 T:139763298125568  NOTICE: Traceback (most recent call last):
13:00:14 T:139763298125568  NOTICE:   File "/home/user/.kodi/addons/plugin.video.shahidmbcnet/default.py", line 2153, in <module>
13:00:14 T:139763298125568  NOTICE:     AddYoutubeLanding(url)
13:00:14 T:139763298125568  NOTICE:   File "/home/user/.kodi/addons/plugin.video.shahidmbcnet/default.py", line 323, in AddYoutubeLanding
13:00:14 T:139763298125568  NOTICE:     link=getChannelIdByUserName(link)#passusername
13:00:14 T:139763298125568  NOTICE:   File "/home/user/.kodi/addons/plugin.video.shahidmbcnet/default.py", line 784, in getChannelIdByUserName
13:00:14 T:139763298125568  NOTICE:     return channelData['items'][0]['id']

Strange :S

**Comment by zombiB** [comment]
some channels are offline ; I am fixing the error now

**Comment by zombiB** [comment]
lebanon fixed ! it will be updated automatically :) enjoy

**Comment by skype007** [comment]
Thank you @zombiB ;) Good work !
