### ISSUE TITLE
f4m not working

### ISSUE THREAD

**Issue by diegofn** [Shani-08/ShaniXBMCWork#223]
Hi Shani
Can you help me how to create a open string i.e. plugin://plugin.video.f4mTester/?url for this link?
http://winsportshds-lh.akamaihd.net/z/winsHDS_1@323475/manifest.f4m?&g=GTQIHEAVBVDI&hdcore=3.6.0&plugin=jwplayer-3.6.0.0&hdcore=2.11.3&g=YFDSUXOICEOR

Notice that if I remove the GET parameters It doesn't work but Kodi doesn't detect parameters.

Thanks!

**Comment by alibbaba** [comment]
It works in kodi. you need to escape & with &amp; and urlencode the url. format is : 
```plugin://plugin.video.f4mTester/?url=URLENCODED```
For example, your url should be like this:
```http%3A%2F%2Fwinsportshds-lh.akamaihd.net%2Fz%2FwinsHDS_1%40323475%2Fmanifest.f4m%3F%26amp%3Bg%3DGTQIHEAVBVDI%26amp%3Bhdcore%3D3.6.0%26amp%3Bplugin%3Djwplayer-3.6.0.0%26amp%3Bhdcore%3D2.11.3%26amp%3Bg%3DYFDSUXOICEORf4m```
