### ISSUE TITLE
shahid arabic Out of order

### ISSUE THREAD

**Issue by gino78240** [Shani-08/ShaniXBMCWork#224]
Hello shani, I have a problem with shahid arabic, when I throw(launch) a chain(channel) I do not arrive has to run the chaîne.il teledunet for example propose me but ca it throws(launches) not. I wish chains(channels) bein sport I have the impression to have a problem with the password. Would have kept silent about an idea?

**Comment by Shani-08** [comment]
teledunet works but for non premium channels, if you are using free account.
