### ISSUE TITLE
error version 1.8.6

### ISSUE THREAD

**Issue by HarryElSuzio** [Shani-08/ShaniXBMCWork#227]
hi shani first of all thank you for your work then let you know that the new update to version 1.8.6 has bugs when adding several lists with a single failure does not try to add the time 2 A conflict is created greetings.

sorry for my English I'm using google translator XD

I would also like to tell you if possible details to a movie or streaming link as director or writer valuation of imdb etc and I saw the synopsis or plot of the movie if it works and gender are added

I'm not sure if I did not find the way to put other data are included or not I could solve this doubt

**Comment by Shani-08** [comment]
fixed in recent release, no idea about the movie details, sorry.

**Comment by HarryElSuzio** [comment]
ok try:
                thumbnail = item('thumbnail')[0].string
                if thumbnail == None:
                    raise
            except:
                thumbnail = ''
            try:
                if not item('fanart'):
                    if addon.getSetting('use_thumb') == "true":
                        fanArt = thumbnail
                    else:
                        fanArt = fanart
                else:
                    fanArt = item('fanart')[0].string
                if fanArt == None:
                    raise
            except:
                fanArt = fanart
            try:
                desc = item('info')[0].string
                if desc == None:
                    raise
            except:
                desc = ''

            try:
                genre = item('genre')[0].string
                if genre == None:
                    raise
            except:
                genre = ''

            try:
                date = item('date')[0].string
                if date == None:
                    raise
            except:
                date = ''


the details of the films you can read KODI would lack add VOTES, DIRECTOR, WRITER, YEAR, TIME

with that data would be added to your addon a super complete listing of all data

I ago my list in your addon and I would love to add these data greetings

and thanks in advance for solving past mistakes

**Comment by HarryElSuzio** [comment]
try:
                thumbnail = item('thumbnail')[0].string
                if thumbnail == None:
                    raise
            except:
                thumbnail = ''
            try:
                if not item('fanart'):
                    if addon.getSetting('use_thumb') == "true":
                        fanArt = thumbnail
                    else:
                        fanArt = fanart
                else:
                    fanArt = item('fanart')[0].string
                if fanArt == None:
                    raise
            except:
                fanArt = fanart
            try:
                desc = item('info')[0].string
                if desc == None:
                    raise
            except:
                desc = ''

            try:
                genre = item('genre')[0].string
                if genre == None:
                    raise
            except:
                genre = ''

            try:
                date = item('date')[0].string
                if date == None:
                    raise
            except:
                date = ''
