### ISSUE TITLE
channels in 4FM never played for me, what are the conditions required?

### ISSUE THREAD

**Issue by ykhehra1** [Shani-08/ShaniXBMCWork#228]
I googled 4fmtester, but unable to find forum for it so asking here. 
 I have your shani repo, and noticed 4fm get updates offen, but channels in it never work for me! It shows 'loading local proxy' but nothing after that. Is something extra needs to be done to get them working, I am trying to use it in Canada if it matters. Thanks

**Comment by Shani-08** [comment]
sorry, the links in f4mTester was just to test those urls, which may or may not work. I know the bbc links are working but you would need UK vpn.
