### ISSUE TITLE
how its work oneplay

### ISSUE THREAD

**Issue by deadpooladdon** [Shani-08/ShaniXBMCWork#229]
well first at all thank you for the livestreampro and all the other addons for kodi 
my problem is i dont know how to put the url of oneplay to work what is the structure to make the call to the script or regex for oneplay i use this website to test http://oneplay.tv/

**Comment by Shani-08** [comment]
Please ask here http://forums.tvaddons.ag/live-video-stream-link-sharing/17239-livestreams-xml-requests-2-a.html
