### ISSUE TITLE
because they do not implement these data to recognize them kodi

### ISSUE THREAD

**Issue by HarryElSuzio** [Shani-08/ShaniXBMCWork#231]
ok try:
thumbnail = item('thumbnail')[0].string
if thumbnail == None:
raise
except:
thumbnail = ''
try:
if not item('fanart'):
if addon.getSetting('use_thumb') == "true":
fanArt = thumbnail
else:
fanArt = fanart
else:
fanArt = item('fanart')[0].string
if fanArt == None:
raise
except:
fanArt = fanart
try:
desc = item('info')[0].string
if desc == None:
raise
except:
desc = ''

        try:
            genre = item('genre')[0].string
            if genre == None:
                raise
        except:
            genre = ''

        try:
            date = item('date')[0].string
            if date == None:
                raise
        except:
            date = ''
the details of the films you can read KODI would lack add VOTES, DIRECTOR, WRITER, YEAR, TIME

with that data would be added to your addon a super complete listing of all data

I ago my list in your addon and I would love to add these data greetings

and thanks in advance for solving past mistakes

**Comment by zombiB** [comment]
i don't think you re in the right place bud
