### ISSUE TITLE
Dramasonline Video on demand list empty

### ISSUE THREAD

**Issue by kaasu** [Shani-08/ShaniXBMCWork#236]
All lists for channels ARY Digital, Hum TV etc are empty. When I go to Top Rated Dramas that list is empty too.

**Comment by Shani-08** [comment]
Updated in version 2.5.0, use the repo to get it automagically.

**Comment by joinfaisal** [comment]
Hi Shani
I updated dramasonline via repi. Whe you click All recent episodes, the list is always empty. I am using firestick and isengard.

**Comment by kaasu** [comment]
I am seeing the same issue i.e. lists for video on demand are always empty. Is there a newer version available? Thanks for all your hard word

**Comment by Shani-08** [comment]
updated again  in 2.5.1
