### ISSUE TITLE
regex broken for dramasonline in 2.5.0

### ISSUE THREAD

**Issue by saqebakhter** [Shani-08/ShaniXBMCWork#237]
not parsing episodes for shows.

**Comment by Shani-08** [comment]
fixed in 2.5.1

**Comment by joinfaisal** [comment]
Hi Shani..Issue is fixed when you click "All Recent Episodes" you see empty page with one link to "Next Page". When you go to next page thats where you see episodes which are one day older. Si in short latest episodes are missing..one day older episodes are seen in second page. At least thats what I see in isengard.
Thanks

**Comment by Shani-08** [comment]
ok gotcha, 2.5.2 got it fixed
