### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by jchirag0221** [Shani-08/ShaniXBMCWork#240]
Hi,

I am intermediate developer and want to contribute to ZemTV addon. I have old jadoo box. Need to help to start with (what kind of softwares need).

Would love to know and little bit help from you so that I can contribute.

Thanks
Chirag

**Comment by Shani-08** [comment]
one of the easiest way would be to see if it supports proxy? if so install fiddler on a window system, enable remote connection and then in jadoo enter the port and ip address.
another solution is to connect a laptop with lan cable and make sure you can browse internet, then create adhoc wifi connection (access point) on that laptop and bridge it(connection sharing) with ethernet card. this means your laptop will be a wifi access point but see all the traffic. so join this wifi from jadoo and run wireshark to sniff it.
there are more than enough ways to sniff the packets. see which ones work for you, you can even have a passive hub, join both the laptop and jadoo and you should see all the packets on wireshark.

**Comment by jchirag0221** [comment]
Ok. Yes, I usually use http://www.connectify.me/ to use my laptop wifi as hotspot. Will try that.
