### ISSUE TITLE
request for script.video.F4mProxy

### ISSUE THREAD

**Issue by avigdork** [Shani-08/ShaniXBMCWork#70]
Hi,
Thanks for all your work.
Could you please add to function playF4mLink in script.video.F4mProxy, 2 more parameters?
 - icon: a link to channel/stream logo to add it to listItem ptoperties.
 - showProgress: a flag to show/hide the progress before playing the stream.

**Comment by relax1000** [comment]
shani? could you please check your inbox on xbmcarabic.com :)
thank you

**Comment by Shani-08** [comment]
Yes I have replied there. Please check.
