### ISSUE TITLE
GLARAB servers, quality & channels

### ISSUE THREAD

**Issue by emadmahdi** [Shani-08/ShaniXBMCWork#74]
Hi Shani,

I hope everything is ok with you ... I know I've been away for couple of months ... and I am sorry for that ... but i was really busy.

Anyway I noticed Yesterday that all GLARAB channels had stopped working suddenly and after investigating I had found that the session ID used in all the URL's had expired.

I did some investigations and experiments and I would like to share what I found ... I am sure you will find a good solution that can cover all the below findings to improve the GLARAB function in your SHAHID plugin ... I also found some new glarab channels and will add them later to your files ... here is what I found:

1- GLARAB supports three stream qualities these are:
Low (300kbps)
Med (500kbps)
HD (900kbps)

2- The GLARAB servers for the Low stream quality are:
38.99.146.40	::	server needs Session ID (& HLS ID)
38.99.146.42	::	server needs session ID (& HLS ID)
38.99.146.43	::	server needs session ID (& HLS ID)
38.99.146.44	::	server needs session ID (& HLS ID)

3- For the Med stream and for the HD stream qualities the servers are:
38.99.146.36	::	server does not need Session ID (nor HLS ID)
38.99.146.37	::	server needs session ID (& HLS ID)

4- The file naming used in the URL's is as follows:
Low quality : xxxxxxxx.m3u8
Med quality : xxxxxxxx_Med.m3u8
HD quality : xxxxxxxx_HD.m3u8

5- The session ID can simply be obtained by using the GLARAB xbmc plugin (plugin.video.glarab) after providing a username & a password obtained from www.glarab.com ... this plugin can login to GLARAB and then by opening any GLARAB channel then this plugin will simply generate a URL that have the session ID which is related to the account used ... and then place that URL in the log file of XBMC (from the whole URL only the session ID is needed).

6- The HLS ID ... I still does not know what it is exactly ... but it looks using any number will do the trick or even removing the whole thing 'hlsid=xxxx' completely from the URL will also do the trick.

7- Sample URLs:
http://glarab.LOW.quality.server:7777/channelname.m3u8?session=sessionID
http://glarab.MED.quality.server:7777/channelname_Med.m3u8?session=sessionID
http://glarab.HD.quality.server:7777/channelname_HD.m3u8?session=sessionID

**Comment by allouch89** [comment]
It seems like they have changed med and hd ip's again

**Comment by jasonalshamary** [comment]
hi everone any help for the hd they change the ip

**Comment by bryan3r3** [comment]
did anyone get the new HD ip? please help!

**Comment by jasonalshamary** [comment]
new ip 
http://38.99.146.158:7777/AlShaab_HD.m3u8
buffs alot
anyone can help?

**Comment by emadmahdi** [comment]
https://github.com/Shani-08/ShaniXBMCWork/pull/117#issuecomment-69473502

**Comment by Jamieanderson123** [comment]
Hello all and hello Shani

What are you getting out of keep publishing the IPs to the world and then getting the servers shut down? We all suffer cause everyone on the internet is sharing those IPs and then they of course have to shut them down. 

These IPs should be build into the shahid plugin and NOT published to anyone and his mother. I know I saw them used on probably 25 sites so far. That's why they shut them down and now everyone is crying cause it is buffering as hell and no one can enjoy it.

Just my 2 cents

Jamie

**Comment by allouch89** [comment]
You are absolutely right.

**Comment by emadmahdi** [comment]
https://github.com/Shani-08/ShaniXBMCWork/pull/117#issuecomment-69516404

**Comment by ehaab** [comment]
Glarab not working. Did any one find new hd ip address for it?

**Comment by kimooo** [comment]
if any one find ip address  shirt with as,,,,, please

**Comment by jasonalshamary** [comment]
Hello everyone so I have The new ip
I will release it soo
Somebody tell me how to auto update
The session: 😉

**Comment by allouch89** [comment]
Are you saying that you have a working HD IP ?

**Comment by ehaab** [comment]
If you have working hd ip then release it !

**Comment by szudena** [comment]
hi guys just change HD to High for some channels
example
http://localhost:4500/channel.flv?server=8.21.48.20&channel=RotanaAflam_High
you dont need session or port
only the zixi http proxy from glarab.com or achams.com or elahmed.com

**Comment by emadmahdi** [comment]
thanks for the info ... we already include it.

**Comment by ehaab** [comment]
8.21.48.20 not working! Any new hd ip fir glarab?

**Comment by szudena** [comment]
it works only with the glarab proxy

**Comment by ehaab** [comment]
Post the proxy that needs to be used

**Comment by mimo424** [comment]
Hi,
How is this support to work? is there any url that can be used in VLC?

**Comment by Shani-08** [comment]
@ehaab Proxy is only available on windows. Go to glarab website and try playing the video, if you dont have proxy it will ask to install it. After than in the addon settings, enable proxy and you should be able to play Hd channels.

**Comment by ehaab** [comment]
@shani-08 . Thanks for reply. I am talking about hd streams that will work on xbmc! The server ip 8.21.48.20 is for sd channels not hd/high! Is there any hd streams for glarab as it used to work in your add in?

**Comment by allouch89** [comment]
@ehaab only low streams from glarab works in xbmc
Unless you use xbmc on windows, you can also watch high/hd streams if you have proxy installed.

**Comment by mimo424** [comment]
@allouch89 when you say HD, are you referring to stream with 720p or 1080p resolution?
Cause iv tried the link solution above on VLC, it works but its defenetly not HD.

**Comment by allouch89** [comment]
Which link above?
When i say HD, i mean the channels that end with _HD, i dont know if its 720p or 360p.

**Comment by ehaab** [comment]
@allouch89 can you give me a _hd channel that will work in vlc? I tried a few non worked!

**Comment by allouch89** [comment]
They only work in the proxy method, for non-proxy method, only low channels are working.

Here is a HD channel with the proxy:
http://localhost:4500/channel.flv?server=8.21.48.20&channel=AlJadeed_HD

You can watch it directly in a browser (tested with firefox).

**Comment by mimo424** [comment]
@allouch89 wel OK, wel the resolution for the _HD channels is 640*480, according to VLC at least.
does anyone have the entire glarab channel list available?

**Comment by allouch89** [comment]
The quality is more than enough for me on a 42" inch TV (based on the HD m3u8 when they used to work).
Channel list is available here in the repo.

**Comment by mimo424** [comment]
ah great, thx, i will look for it :). Keep up the good work

**Comment by szudena** [comment]
new solution for glarab without to start proxy available i will post it later

**Comment by allouch89** [comment]
HD channels?

**Comment by szudena** [comment]
yes

**Comment by allouch89** [comment]
nice, cant wait.

**Comment by szudena** [comment]
it is a ip from tel.d.net. server  he have run die proxy on his server 
we need just 
http://his ip here:4500/channel.flv?server=8.21.48.20&channel=AlJadeed_HD

**Comment by ehaab** [comment]
szudena is that solution will work on vlc/xbmc/jw player as well ?

**Comment by szudena** [comment]
yes
on all device and os

**Comment by szudena** [comment]
i wil post it first for  gigablue then for the other i waiting a frind testi if you know him

**Comment by allouch89** [comment]
what is gigablue ?

**Comment by szudena** [comment]
linux receiver enigma2

**Comment by szudena** [comment]
give me 10 minutes then post it here

**Comment by ehaab** [comment]
szudene the server address that you posted doesn't belong to glarab . Is this different provider ?

**Comment by allouch89** [comment]
it is the proxy from glarab, that you can use, instead of installing in your self.
this way you can watch the streams on any os.

**Comment by szudena** [comment]
so guys

change the following
http: // localhost: 4500 / channel.flv

to

http://178.33.241.201:4500/achamsCOM.flv

have fun

**Comment by Shani-08** [comment]
perhaps we remove this here and i could add this ip in the code directly?

**Comment by szudena** [comment]
yes better

**Comment by Shani-08** [comment]
Please do not change the xml file., i will add this as first try, if this doesn't work then our usual local proxy will work.

**Comment by Shani-08** [comment]
OK its working. so i need to create a settings if user want to disable the common proxy just in case this goes down and cause freezing because of people using it.

**Comment by ehaab** [comment]
shani-8 can you tell me how to make this solution work on vlc?

**Comment by mimo424** [comment]
@ehaab you simply use this url structure for VLC:
http://178.33.241.201:4500/channel.flv?server=8.21.48.20&channel=RotanaAflam_High

**Comment by Shani-08** [comment]
Please do not post these ip addresses on here for public. Edit and remote.
Shahid is now updated with 3.5.1 which will use the shared proxy and if doesnt work will use local proxy.

**Comment by hawwach** [comment]
@Shani-08 Man you're the best, tested and working properly.
@szudena Thanks for your effort.

**Comment by kimooo** [comment]
shani-08 you said don't post it here  what about us ,,,, please could you send it to me in a private message
Thanks

**Comment by Shani-08** [comment]
Anyone wants the url send email to taacc14 at gm a  il. c om

**Comment by szudena** [comment]
i thing is down

**Comment by kimooo** [comment]
I send email to you

**Comment by jasonalshamary** [comment]
Please what the link

**Comment by jasonalshamary** [comment]
Okay guys so if this is a headache
So I got that Glbox 
And I'm willing to share my links
Does anyone knows how to get the links from the box and I will share them with you guys

**Comment by szudena** [comment]
@jasonalshamary 
teamviewer?

**Comment by jasonalshamary** [comment]
What do you mean?

**Comment by szudena** [comment]
do you have teamviewer

**Comment by jasonalshamary** [comment]
I have the glarab box

**Comment by szudena** [comment]
if you have fritzbox you can Sniffing HTTP traffic or if the box are android box you can plug the box with usb cabel to pc and sniff the traffic

**Comment by szudena** [comment]
if you need help i can help you with teamviewer

**Comment by jasonalshamary** [comment]
Okay give me a tutorial or guide me to it and we can use my box or if you want to watch TV I don't care it's not the end of the world i wanna help everyone

**Comment by szudena** [comment]
do you have a fritzbox router?

**Comment by jasonalshamary** [comment]
No but my 
router comes with a USB and the Glbox comes with USB

**Comment by szudena** [comment]
have the glbox a android os?

**Comment by jasonalshamary** [comment]
Good question I would I know

**Comment by szudena** [comment]
if yes aktiv the usb debugging in the setting on device 
and install android studio on pc
https://developer.android.com/tools/debugging/debugging-studio.html

**Comment by jasonalshamary** [comment]
Okay I'll try it but if is not android
Then what

**Comment by allouch89** [comment]
Is it possible to connect to the internet with wifi from the box?
Then you can connect the box with a proxy from your computer and use something like wireshark to sniff the packets

**Comment by jasonalshamary** [comment]
Lol i'm downloading wire shark. Right now. In the box is on Wi-Fi so now what

**Comment by allouch89** [comment]
When you connect to wifi, do you see any option where you can set a proxy?

**Comment by jasonalshamary** [comment]
No. Just give me the IP to the Box and a DNS

**Comment by allouch89** [comment]
Maybe you can use DNS instead, im not sure. I have only used it with proxy once.

**Comment by jasonalshamary** [comment]
Okay so what's the link like the DNS and .M3u8 can you send me a link

**Comment by Shani-08** [comment]
Let me know if you need help. 
My suggestion would be to use windows laptop. Connect it to router via lan cable and make sure you can browse Internet. Then make you wireless card an adhoc access point and give it a name. This will be your wifi that you want to connect to from glbox. 
Make sure the Internet sharing is on between  wlan and lan connection. This way the box send all the data which will go via lan cable of the laptop and running wireshark will get you all the packets. 
Save those files and send it to one of us.

**Comment by allouch89** [comment]
it seems like the shared proxy is not working anymore, i guess too much traffic?
because when you check json_version.htm, it response, after a minute or so. but when playing a channel, it just timeout.

**Comment by emadmahdi** [comment]
@Shani-08 ... can you please send me some details about the shared proxy privately to my email ... may be I can find more or similar proxies ... I knew that gl has a proxy installed somewhere and I already mention that in one of the old comments ... plus last week i did a quick network scan but I could not find it ... may be I can try a deeper scan ... but i prefer to get some details from you first ... let me know.

**Comment by allouch89** [comment]
its exactly the same method, its just an public ip address instead of 127.0.0.1

**Comment by Shani-08** [comment]
Email sent

**Comment by hassuni** [comment]
Thanks guys for what are you doing.

by me is not working proxy and shared proxy .
witch version of proxy we should install 
I have installed this one glarab_http_proxy-1.4.0.5571

**Comment by allouch89** [comment]
just install the latest version.

**Comment by emadmahdi** [comment]
ok ... the ip that is used as a shared proxy does not belong to gl network ... it belongs to another company in France called "***" they are an ISP and they are not specialized in live video streaming like gl ... plus this shared proxy might just be a small server on their network installed and set by one of their clients.

Anyways ... the good news is they are using version 1.4.0.5571 of the proxy ... which is available on www.4shared.com ... and I guess it is reliable enough that is why they chooses this particular version.

**Comment by szudena** [comment]
the shared proxy belong to the site teledunet.com

**Comment by szudena** [comment]
for now both not work local and shared proxy

**Comment by hassuni** [comment]
proxy work for me on PC, try 2M  Proxy HD

**Comment by jasonalshamary** [comment]
What the link

**Comment by szudena** [comment]
http://127.0.0.1:4500/channel.flv?server=38.99.146.36&channel=M2Morocco_HD&port=2077&session=0888226eb3f30a136f5e51b986ebf45e4d8d6217902f1447abb075d058b1eecc

**Comment by jasonalshamary** [comment]
It's not working 


http://127.0.0.1:4500/channel.flv?server=38.99.146.36&channel=M2Morocco_HD&port=2077&session=0888226eb3f30a136f5e51b986ebf45e4d8d6217902f1447abb075d058b1eecc

**Comment by szudena** [comment]
you must start the glarab proxy on your pc

**Comment by ehaab** [comment]
can any one tell how we can setup such a proxy ourself in a webiste ? is it php proxy ? how we pass the parameters to the proxy?

**Comment by Shani-08** [comment]
I think it's just a windows server running glarab proxy and port 4500 is forwarded to that machine. Anyone should be able to do this, it's same when you install proxy on your network windows machine, just that this is exposed to the Internet.

**Comment by emadmahdi** [comment]
i finished scanning using two methods ... video & http ... but still could not find any gl proxy installed on 4500 ... i wonder if they have special customized proxy version that can work on other ports ??!!!!!

**Comment by Shani-08** [comment]
I am disabling the share proxy. When we get it working or if you want to talk test then out the False in default.py file. 
Look for glproxyCommonDisabled=true

**Comment by emadmahdi** [comment]
ok ... Thanks Shani.

**Comment by Shani-08** [comment]
Also you have low settings for NOm proxy so you can now use all ip for proxies while use that one for Non proxy.

**Comment by jasonalshamary** [comment]
What the link for non proxy I don't have Xbmc I wanna see it so I can try my ip

**Comment by emadmahdi** [comment]
I saw the two lists ... but both have the same label ... i tried download but it did not fix the labels.

Also you said the variable for both lists will be the same ... what's the difference ... why not separating the variables too ? ... for the gl file i can fix it easily.

**Comment by emadmahdi** [comment]
@jasonalshamary ... try this link http://38.99.146.42:7777/Beladi.m3u8 ... it does not need session id.

**Comment by jasonalshamary** [comment]
Thanx bro but this link is for the low not hd

**Comment by emadmahdi** [comment]
currently no other quality is available for the non-proxy method ... anyways just add _HD or _Med to the end of the channel name to get other qualities (if there is any).

**Comment by allouch89** [comment]
@jasonalshamary i thought you had the GL box, why are you trying these links and proxy links ?

**Comment by jasonalshamary** [comment]
Because I told you I want to try everything I can to share my IP and links with everyone on the site

**Comment by allouch89** [comment]
Appreciate it, but shouldnt you try to listen to the packets from the box then, instead of trying the links we already have?

**Comment by jasonalshamary** [comment]
First of all I am at work right now but when I tried it earlier there is all kind of IP's i'm not going to give you an IP where somebody can hack me I'm going to look for the right one

Second of all in the GL box there is two sections one a section the channels on their website is there the HD channels that we are getting is not from their box I mean they are there but they are  streaming them from different websites

**Comment by allouch89** [comment]
Well the IPs that we have aint working anymore, so i dont think that you will find any working links with the current IPs that we have, that would be my guess.
You can just check if your own IP is in those links, you can use http://whatismyipaddress.com/ to see what your ip is.
Why would you think that we will hack you? You send it to one of our emails. that way you dont have to publish it for everyone.

**Comment by allouch89** [comment]
If you trust that i wont hack or attack your IP address, you can send your findings to my email and I will try to see if I can make any sense of it. My email is allouch@live.dk

**Comment by jasonalshamary** [comment]
No no I didn't say you you will Hack me 
I'm saying this soon we both anything everybody reposted and the whole global that's why did GL Arabs keep changing their IP and port all I'm saying this when I figure out how to get links from my box and I will share them with you guys and for your knowledge we can hide the links somehow so they don't be posted all over the Internet and they keep on line for everyone to watch TV and enjoy themselves 
And To me it's  all about  knowledge
And learning new things

**Comment by allouch89** [comment]
I see your point and I agree. But there will always be someone out there that can sniff the packets and get the IP's from xbmc or whatever.
Anyway, thanks sharing and let us know if there is anything we can help with.

**Comment by jasonalshamary** [comment]
Thank you and hope we will work something out

**Comment by szudena** [comment]
still working glarab HD?
for me stoped  with all ips

**Comment by allouch89** [comment]
None of the HD IP's is working anymore..

**Comment by szudena** [comment]
thx I figured that

**Comment by ehaab** [comment]
any hd ip for glarab?

**Comment by ehaab** [comment]
can we use php proxy instead of localhost proxy for hd streams?

**Comment by mimo424** [comment]
What about the other IPs for non HD, are they working?

**Comment by jasonalshamary** [comment]
Hear you go boy some channels for now



ARABIA HD..
‪#‎EXTINF‬:-1,art _aflam
rtmp://162.212.176.107:1935/art_aflam_2/globaltv-art_aflam_2.stream
#EXTINF:-1,alhayat 1 
rtmp://162.212.176.107:1935/alhayat_1/globaltv-alhayat_1.stream
#EXTINF:-1,alhayat cinema 
rtmp://162.212.176.107:1935/alhayat_cinema/globaltv-alhayat_cinema.stream
#EXTINF:-1,rotana_cinema 
rtmp://162.212.176.107:1935/rotana_cinema/globaltv-rotana_cinema.stream
#EXTINF:-1,rotana_clip
rtmp://162.212.176.107:1935/rotana_clip/globaltv-rotana_clip.stream
#EXTINF:-1,rotana_music
rtmp://162.212.176.107:1935/rotana_music/globaltv-rotana_music.stream
#EXTINF:-1,dream_1 
rtmp://162.212.176.107:1935/dream_1/globaltv-dream_1.stream
#EXTINF:-1,melody_aflam 
rtmp://162.212.176.107:1935/melody/globaltv-melody.stream
#EXTINF:-1,zee_alwan 
rtmp://162.212.176.107:1935/zee_alwan/globaltv-zee_alwan.stream
#EXTINF:-1,fox_movies 
rtmp://162.212.176.107:1935/fox_movies/globaltv-fox_movies.stream
#EXTINF:-1,Moga_Comedy 
rtmp://162.212.176.107/moga_comedy//globaltv-moga_comedy.stream
#EXTINF:-1,cairo_cinema 
rtmp://162.212.176.107:1935/cairo_cinema/globaltv-cairo_cinema.stream
#EXTINF:-1,cairo_drama 
rtmp://162.212.176.107:1935/cairo_drama/globaltv-cairo_drama.stream
#EXTINF:-1,abu_dhabi
rtmp://162.212.176.107:1935/abu_dhabi/globaltv-abu_dhabi.stream
#EXTINF:-1,abu_dhabi_drama 
rtmp://162.212.176.107:1935/abu_dhabi_drama/globaltv-abu_dhabi_drama.stream
#EXTINF:-1,national_geo 
rtmp://162.212.176.107:1935/national_geo_ad/globaltv-national_geo_ad.stream
#EXTINF:-1,MBC 3 
rtmp://162.212.176.107:1935/mbc_3/globaltv-mbc_3.stream
#EXTINF:-1,MBC 4 
rtmp://162.212.176.107/mbc_4/globaltv-mbc_4.stream
#EXTINF:-1,mbc_max 
rtmp://162.212.176.107:1935/mbc_max/globaltv-mbc_max.stream
#EXTINF:-1,echorouk tv 
rtmp://162.212.176.107:1935/echorouk_tv/globaltv-echorouk_tv.stream
#EXTINF:-1,Nile Comedy 
rtmp://162.212.176.107:1935/nile_comedy/globaltv-nile_comedy.stream
#EXTINF:-1,Nile Drama 
rtmp://162.212.176.107:1935/nile_drama/globaltv-nile_drama.stream
#EXTINF:-1,Nile Cinema 
rtmp://162.212.176.107:1935/nile_cinema/globaltv-nile_cinema.stream
#EXTINF:-1,LBC 
rtmp://162.212.176.107/lbc_europe/globaltv-lbc_europe.stream
#EXTINF:-1,Alriadia_sport 
rtmp://162.212.176.107:1935/alriadia_sport/globaltv-alriadia_sport.stream
#EXTINF:-1,tunisia_national_1 
rtmp://162.212.176.107:1935/tunisia_national_1/globaltv-tunisia_national_1.stream
#EXTINF:-1,tunisia_national_2 
rtmp://162.212.176.107:1935/tunisia_national_2/globaltv-tunisia_national_2.stream
#EXTINF:-1,nessma 
rtmp://162.212.176.107:1935/nessma/globaltv-nessma.stream
#EXTINF:-1,hanibal 
rtmp://162.212.176.107:1935/hanibal/globaltv-hanibal.stream
#EXTINF:-1,medi1 
rtmp://162.212.176.107:1935/medi_1_sat/globaltv-medi_1_sat.stream

**Comment by Shani-08** [comment]
Please do not post links here. In anycase this issue is not resolved so do not post anything anymore here. create new issue if you have to discuss any issue, for links, email people thanks

**Comment by jasonalshamary** [comment]
I'm sorry I was trying to help some of the guys to watch tv that's all ..😩

**Comment by Shani-08** [comment]
I get that and I doubt your good intention but we ought to find better ways to communicate.

**Comment by jasonalshamary** [comment]
Ok by email?

**Comment by Shani-08** [comment]
Yes.

**Comment by kimooo** [comment]
any news ? about new ip address

**Comment by jasonalshamary** [comment]
Shani email men 
I got the new ip😀

**Comment by kimooo** [comment]
good news man ,,,,we are waiting

**Comment by allouch89** [comment]
@jasonalshamary sounds good, i would like to confirm if you dont mind.
allouch@live.dk

**Comment by jasonalshamary** [comment]
Any one want just email me 
Jasonalshammary@hotmail.com

**Comment by allouch89** [comment]
Thats the proxy that we found about a month ago, works sometimes but is overloaded most of the time.

**Comment by jasonalshamary** [comment]
If want the new one email me man

**Comment by allouch89** [comment]
you have already sent it to me?

**Comment by jasonalshamary** [comment]
allouch89 
Yes I send it to u

**Comment by allouch89** [comment]
Ok and im telling you, thats the proxy that we found about a month ago, works sometimes but is overloaded most of the time. Its not the new IP for glarab, is an IP poiting for the glarab proxy.

**Comment by jasonalshamary** [comment]
Here I'm going to post it

Have fun

http://178.33.241.201:4500/channel.flv?server=216.66.42.85&channel=LDC_High&port=2077&mode=3&user=1673551211&session=e543769479e71f4ece810a8d9242bfc1bda2c34a78e9381f32e571b73d81b2c0a299017ce29bf1aa

**Comment by allouch89** [comment]
Why would you do that.. I have deleted it, please dont post it again.

**Comment by ahmadwalid231** [comment]
Hello, I have been working on glwiz, which uses same kind of authentication like glarab and wondering if anybody can help me? As I read above posting links is forbidden for now, so if anybody want to help, then I can provide more information.

**Comment by jasonalshamary** [comment]
Email me at jasonalshammary@hotmail.com

**Comment by bolbol87** [comment]
hi

**Comment by bolbol87** [comment]
any  new ip address

**Comment by jasonalshamary** [comment]
Hello every one so I got new ip
New link I'm not going to post it
Because of allouch89
He delet my posts I don't know why
He don't like sharing things with people he like to add links on her Xbmc files 
And get all the credit it's all god 
So I'm workin on makeing a program
We in going to add all the IP's
And will update the season session automatic so be patient and I'll see you guys this week sometimes 

One love

**Comment by allouch89** [comment]
What are you talking about.. You are just being rude now!
I only deleted it because we agreed on not sharing something like that in the public, since whenever we post anything in the public it only last for 2 days and then they close or change the settings and are useless again..
I told you that loud and clear, but you didnt get it i guess.. And I also told you that the "new ip" that you posted was a proxy that we already had found a while back and it wasnt that good since it is overloaded most of the time!
And just to be clear, i dont take any credit for anything i do in here, and i dont even use xbmc anymore and havent done so for over 3 months!

**Comment by allouch89** [comment]
Besides from all that, keep up the good work! Im sure alot of people appreciate what you are trying to do and hope you succeed with it.

**Comment by jasonalshamary** [comment]
@allouch89

Look man i'm sorry that you thought I was rude and I'm sorry if I offended you
All I was saying was a lot of people
They have no clue how to use XBmc
Or other software's or even getting links
They just want to watch TV 
And for the links you trying to protect
Bro And I going to last forever
And what I was trying to do is help people
Some people don't have money to buy TV
Boxes or iptv or zap TV
All I'm saying is this just try to help each other share stuff together
And when I posted the link
You said you have the same IP
But is not working good
Can you please tell me the IP

So I can If you using the same IP

Bro would you believe me
If told you I'm useing
The same old ip

38.99.146.37. And 36

**Comment by allouch89** [comment]
I know that alot of people needs our help to watch tv, but we cant share everything in the public.
What we can do is to update the settings in shahid plugin so people can enjoy the channels in xbmc, this is what this github project is for after all.
If we share everything in the public, it wont last long before they shut it down again.
Its the same IP that you sent when I deleted it, the proxy IP which looks something like this:
http://....:4500/channel.flv... However we agreed to not publish in public discussions anymore, so i cant write more than this.

**Comment by allouch89** [comment]
I hope you dont mind that i edited your post, so now i will update the XBMC to make it work with those IPs, please try not to post anything in the public like that. They will change or shut it down again.

**Comment by allouch89** [comment]
Its because the http links have been removed from the glaraburls.xml file, i hope that shani or emad still have somewhere. When they get added, the glarab will work again in shahid xbmc.

**Comment by allouch89** [comment]
I'll add the HD my self, i just hope they still have a backup from the old glarab links, then they can replace the ones i'll add in a bit

**Comment by jasonalshamary** [comment]
It's all good man
I really hate 
Xbmc but I wish you guys all the best
And the link they just posted
Forget about a man it sucks
However I'm going to release an app very soon hopefully everyone like it and everything is going to be update automatic

**Comment by allouch89** [comment]
An app for what, android?

**Comment by jasonalshamary** [comment]
Sorry bro I meant to say a program
For windows

**Comment by allouch89** [comment]
Okay sounds good, keep up the good work!

**Comment by jasonalshamary** [comment]
Thanks bro I will replace it soon
I just have to talk to my friend about it

**Comment by emadmahdi** [comment]
@jasonalshamary ... Thanks for your efforts ... we appreciate your help ... please let us know if you find anything new.

@allouch89 ... Although i do appreciate your attitude to protect the availability of gl channels but please note that ... this is a place for people to communicate ... and without the help from people like @jasonalshamary ... this plugin will not be great the way it is now ... people have the right to publish their own work ... we are not here to control people ... we are here to listen and improve this plugin.

@allouch89 ... I personally do not appreciate people who deletes my words without my permission ... you do have the right to comment and post ... and other people also have this same right ... plus these comments are not only for you ... it is for the whole team ... so please do not delete others comments without their own permission ... you can simply ask people to do so (if they accepts your idea).

@allouch89 & @jasonalshamary
Concerning keeping the ip's secret ... it does not make any sense ... simply because the ip's are clearly visible in the settings and also they are visible during the "Try All" ... plus gl does not need us to tell them what is working on their servers and what is not ... they simply can monitor the traffic on the servers to know what is going on ... @Shani-08 said once "we are not the only smart people in the world".

@allouch89 ... Thanks for your efforts and don't worry about the gl xml file ... I will try as soon as possible to rewrite the whole file after testing all the links.

@Shani-08 ... i don't know for how long the non-proxy HD & MED will be available or if it is now available only for testing purposes ... but i still think we do need to separate their ip's in the settings page ... same what you did with the LOW ... i personally use both methods proxy & non-proxy at the same time.

**Comment by emadmahdi** [comment]
@allouch89 ... Thanks for your efforts and don't worry about the gl xml file ... I will try as soon as possible to rewrite the whole file after testing all the links.

@Shani-08 ... i don't know for how long the non-proxy HD & MED will be available or if it is now available only for testing purposes ... but i still think we do need to separate their ip's in the settings page ... same what you did with the LOW ... i personally use both methods proxy & non-proxy at the same time.

**Comment by jasonalshamary** [comment]
Lol guys guys
Just focus on this ip
38.99.146.37 
That's all I have to say till I release my program

**Comment by jasonalshamary** [comment]
Ps
Forget about  the Xbmc and nonsense files

**Comment by emadmahdi** [comment]
@jasonalshamary ... incase you don't know what Lol means ... it means ... Laughing out loud ... hence is there anything funny that makes you Lol or it is just your attitude of disrespecting people ??!!!!!

**Comment by jasonalshamary** [comment]
My attitude?
So I can't laugh now
In case you didn't know life's too short to Cry and I was just trying to be friendly
But I just realize your a fucking tool
Whoever is running the site just delete my account 
Just bunch of guys don't like to help and hiding Lanks and ip's just like baby's see ya's have fun

**Comment by emadmahdi** [comment]
@jasonalshamary ... I think you heard the saying ... Laughing for no reason is lack of manners ... and in Arabic it is translated to ... الضحك بلا سبب من قلة الادب

As for you ... your laughing and your answers as well as your words ... it all shows clearly and obviously that you have no manners at all ... As for us ... it is obvious that we are too polite compared to you ... Hence go and use your bad manners, bad language & bad attitude somewhere else ... we are group of people who respects each other and we have no place for bad people like you.

**Comment by jasonalshamary** [comment]
Ok that's good have a good life man
I am rude.
I have no manners.
You are right
And I am stupid for trying to help.... Lol
Laughing is good for you sometimes
And you just mad cuz I have the links that's u are looking for all year long
And u don't
It's all good man just email me and I'll sent them to you
And u can go and say hey guy I have the links I worked hard for bro u need to go to sleep cuz you don't know nothing all you want is credit I'm gonna give you all the credit in the world cuz u are trying to fight with me for nothing I don't know y

**Comment by allouch89** [comment]
If you guys cant figure out to get along, you should just stop this discussion and move on :)

**Comment by emadmahdi** [comment]
@jasonalshamary ... if the price for your info is bad manners, bad attitude and bad language ... then keep all your info for yourself ... we do not need anything from bad people like you ... go and find yourself people like you because it is very obvious that we are too polite compared to your mouth.

**Comment by jasonalshamary** [comment]
Dude you need to relax

**Comment by Shani-08** [comment]
Everyone, calm down. 
Only way we can move forward is treating everyone with respect. Remember no one is charging any money and all of them trying to help each other and everyone else by spending our time for free. 
So anyone trying to help, just encourage but Please no more name calling or fighting. No one is more or less clever here. 
No more discussion on this thread anymore, thanks. Please see the issue has been closed, open a new one of we need to talk about anything.

**Comment by hassuni** [comment]
@jasonalshamary  Can do me a favorites please. if it possible to find the complete channels list name as m3u8?
Like CairoComedy.m3u8, I think we are  missing a lot of chanels
Thanks

**Comment by norhan76** [comment]
R u guys updating the channels bec they r buffering a lot now, thanks a lot

**Comment by hassuni** [comment]
try to change your device.

**Comment by jasonalshamary** [comment]
@hassuni
I'm sorry man
I wish I could but I promised myself not to bother anymore help anyone
I feel so bad for saying it
So good luck my friend

**Comment by hassuni** [comment]
@jasonalshamary thanks anyway

**Comment by hmemar** [comment]
Well said shani

Regards

Husham Memar

**Comment by szudena** [comment]
hi friends, I do not know if you've noticed that glarab hd is fixed 
can any one test if he have same buffering problem thx

**Comment by moe1999** [comment]
No it's perfect as of now for me.

**Comment by szudena** [comment]
ok thx for test

**Comment by bolbol87** [comment]
Hi 
Can anyone send some arabic links
Thanx

**Comment by Shani-08** [comment]
Thanks @szudena i tried and it looks great!

**Comment by mimo424** [comment]
is there anyway to get the full channel ip's to use on external players such as VLC?

**Comment by szudena** [comment]
@shani thx for test

**Comment by norhan76** [comment]
Thanks guys for the great work.

**Comment by hassuni** [comment]
@szudena thanks

**Comment by moe1999** [comment]
Is it possible for u to snoop the m3u file of GLarab

**Comment by bolbol87** [comment]
can anyone send me glarab file please
thanx
(nabilfahmy87@yahoo.com)

**Comment by Yaser7440** [comment]
Plz  guys, can you send me the file 

Thinks alot

m.ghadouni@gmail.com

**Comment by szudena** [comment]
glarab dont work in m3u because dynamic session
install kodi and the addon shahidmbcnet to get glarab

**Comment by bolbol87** [comment]
I got  new ip address end with (ts)
for exchange with another ip
nabilfahmy87@yahoo.com
thanx

**Comment by norhan76** [comment]
Does anyone have a problem with GLARAB Again, not working for me 😢 on android box.

**Comment by szudena** [comment]
fixed

**Comment by moe1999** [comment]
Can you get livetv.tn servers

**Comment by norhan76** [comment]
Thank u so much.

**Comment by moe1999** [comment]
Hey can you get the live tv.tn servers.

**Comment by mbenjell** [comment]
can anyone please send me glarab file please
Thank you

(mohamedwydad@Hotmail.com)

**Comment by Muhand** [comment]
GALarab Servers are down again, anyone experiencing the same problem?

**Comment by mbenjell** [comment]
Yes GlARAB not working for some reason

Date: Wed, 6 May 2015 21:08:00 -0700

**Comment by szudena** [comment]
fixed:)

**Comment by mbenjell** [comment]
Awesome - thank you

**Comment by moe1999** [comment]
Not working

**Comment by mbenjell** [comment]
It's working but only low quality

**Comment by moe1999** [comment]
How about the hd

**Comment by mbenjell** [comment]
No HD is not working

**Comment by moe1999** [comment]
Can you get TV from like satellites and start to stream them

**Comment by mbenjell** [comment]
No because are not available in my country

**Comment by infernape211** [comment]
Experiencing same issues as mbenjell. I don't even see Low as an option when trying to connect. Only a handful of channels work with non-GLArab servers.

**Comment by szudena** [comment]
Sorry, I will not fix it because few hours later down

**Comment by infernape211** [comment]
What do you mean? Is it normal for it to go down and go back up later?

**Comment by mbenjell** [comment]
I don't think GLARAB goes down too often, it just the quality get change from HD to low. maybe because they change the ip address.

Date: Fri, 8 May 2015 17:25:36 -0700

**Comment by infernape211** [comment]
I don't see the option for low for most channels =/

Maybe my configuration is off because I'm unable to load anything.

**Comment by mbenjell** [comment]
Try to uninstall it and install it again!

Date: Fri, 8 May 2015 18:39:48 -0700

**Comment by infernape211** [comment]
I've done that, no luck. It only shows me the GLArab HD option.

**Comment by szudena** [comment]
not all HD channels are available in low

**Comment by Shani-08** [comment]
nothing to discuss at the moment
